cal-adapt/climakitae

- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/selectors.py
- setup.cfg
The following was corrected / added:
- fixed a mis-stated assertion error in generate() that prevented it from sub-setting regions
- added a map that shows the sub-setting area selected, as a param view
- added state outlines, and county and watershed outlines within California as additional area options
- added additional error checking, and hiding scenario options that are not available for a resolution
> Select geoms

- climakitae/data_loaders.py
Sounds like we're going to need to remove this, so might as well get this version checked into 'main'.
> No progress bar on generate.

- climakitae/threshold_tools.py
for _get_aicc_stat_ i changed _ValueError_ to _(ValueError, ZeroDivisionError)_ to account for any errors with the l-moments and division by zero.
> adding fix to aicc function for threshold tools

- climakitae/timeseriestools.py
- setup.cfg
First pass at timeseries tools -- selection panel in place. Usage demo-ed in cae-notebooks/timeseries_example.ipynb
> Timeseriestools

- climakitae/data_loaders.py
- climakitae/selectors.py
Minor updates from comments by @bkg on PR#41
> Incorporating comments from PR#41

- climakitae/data_loaders.py
Found an overlooked error introduced by a change in last PR.
> Need cartopy CRS for transform_points method.

- climakitae/core.py
- climakitae/data_loaders.py
This only changes a few lines of code. I missed this bug when fixing merge conflicts with main after we merged Naomi's PR. It has to do with the DataArray naming conventions in the data_loaders.py module.
> Small bug fix due to inconsistencies with main 

- climakitae/data/variable_descriptions.csv
Very small pull request for a typo in the data descriptors file
> fix typo in wind description

- climakitae/explore.py
I've made some small(ish) changes since WG 4, listed below: 
1. Postage stamp plots are now interactive. They are made with hvplot.image(). Everything is a tiny bit slower than with the static plots, but I think it's worth it, because these maps are rad. 
3. The GMT context plot includes all the SSPs now (1-1.9 and 1-2.6 as well). It includes options to show all SSPs on the same plot, or to just show the selected SSP. I've also added labels to the confidence interval lines that improve the readability of the plot (at least, I think so!). 
https://user-images.githubusercontent.com/66140951/188938967-e47ebac6-936a-4133-a2a9-f169edb9b793.mov
> app.explore(): Interactive plotting & improvements to GMT context plot

- climakitae/core.py
- climakitae/explore.py
- climakitae/tmy.py
This PR simply removes the TMY code from app.explore. Related code was moved to tmy.py for further development.
> app.explore(): Remove typical meteorological year panel 

- climakitae/explore.py
- climakitae/tmy.py
This PR has expanded documentation in the GMT context plot and both postage stamp tabs, as well as a new panel to show info about the anomaly calculations. It also adds a "tip" box in the first postage stamp tab telling users how to use the plotting toolbar. Lastly, I've added back in the 4 deg warming option! I took some creative liberties here, trying to develop features requested by stakeholder, and would love some feedback on what people think.
> app.explore(): Documentation improvements & Added 4 deg warming option

- climakitae/core.py
- climakitae/explore2.py
This creates an additional class so that we can call various explore methods with:
```python
app.explore2.TMY()
app.explore2.thresholds()
```
I have named the attribute `explore2` for now until we decide how to handle or rename the existing app.explore() method.
> Add explore class to Application

- climakitae/explore.py
This PR replaces regionmask with rioxarray in explore.py, thus resolving the inconsistencies with the area subsetting method introduced in past PRs. I also deleted some unused packages in the import statements.
> Explore error fix

- climakitae/tmy.py
Suuuuper quick PR: there were some long lines of descriptive text and formatting, which is resolved here for easier readability, as well as deleting one old comment.
> Cleans up long code lines in AMY

- climakitae/data_export.py
This is a line-by-line merge of the past two weeks of changes to `data_export.py` because I was branching off of `main`.
> franken code which merges my export PRs from the past 2 weeks

- climakitae/data_export.py
This PR fixes the `strip()` issue #102 and cleans up whitespace and formatting in `export_data.py`
> Fix CSV metadata

- climakitae/data_export.py
- Changed errors to exceptions
- Spruced up some error messages related to data dimensionality when exporting to geotiff
- Wrote clearer error message when trying to export multivariate dataset to CSV or geotiff
- Attempt to export datasets of various shapes to geotiff
- Attempt to export multivariate datasets to CSV or geotiff.
Let me know how the error messages look.
> clearer error messages; formatting

- climakitae/catalog_utils.py
- climakitae/core.py
- climakitae/data_export.py
- climakitae/data_loaders.py
- climakitae/derive_variables.py
- climakitae/explore.py
- climakitae/metadata_update.py
- climakitae/selectors.py
- climakitae/threshold_panel.py
- climakitae/threshold_tools.py
- climakitae/timeseriestools.py
- climakitae/tmy.py
- climakitae/unit_conversions.py
- climakitae/utils.py
- climakitae/view.py
- climakitae/visualize.py
- climakitae/warming_levels.py
- environment.yml
This is a BIG PR that cleans up the code for styling and formatting. It is a first pass and will need to be reviewed carefully to see that I haven't introduced any syntax errors.
@bkg Please see if I've screwed up the PEP8 styling and make edits where appropriate. Thanks!
> First run through the code to cleanup styling

- climakitae/catalog_convert.py
- climakitae/core.py
- climakitae/data_export.py
- climakitae/data_loaders.py
- climakitae/derive_variables.py
- climakitae/explore.py
- climakitae/metadata_update.py
- climakitae/selectors.py
- climakitae/threshold_panel.py
- climakitae/threshold_tools.py
- climakitae/timeseriestools.py
- climakitae/tmy.py
- climakitae/unit_conversions.py
- climakitae/utils.py
- climakitae/view.py
- climakitae/visualize.py
- climakitae/warming_levels.py
- tests/conftest.py
- tests/create_test_dataset.py
- tests/derive_variables/test_derived_variables.py
- tests/threshold_tools/test_thresholds_exceedance.py
- tests/threshold_tools/test_thresholds_returns.py
- tests/timeseriestools/test_timeseriestools_monthly.py
- tests/unit_conversions/test_unit_conversions.py
Simple PR to clean up code in `main` using black.
> Code cleanup using black

- climakitae/tmy.py
This is a helper function used in the AMY notebook.
> Add helper function to return julian day bounds for AMY months

- climakitae/catalog_convert.py
- climakitae/cluster.py
- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/derive_variables.py
- climakitae/explore.py
- climakitae/selectors.py
- climakitae/tmy.py
- climakitae/utils.py
- climakitae/warming_levels.py
- tests/derive_variables/test_derived_variables.py
- tests/timeseriestools/test_timeseriestools_monthly.py
This PR lints the codebase using black so that it will pass the new black test workflow.
> Lint codebase using black

- climakitae/data/variable_descriptions.csv
- climakitae/data_loaders.py
- climakitae/derive_variables.py
- climakitae/selectors.py
- tests/derive_variables/test_derived_variables.py
This is a total rework of app.select to make it look shinier! And fancier! I've added the following things: 
1. New spatial subsetting options: (1) Electric Demand Forecast Zones and (2) IOUs & POUs 
2. Data selections and location subsetting are now part of the same card, in different tabs 
3. New warning if you've selected data outside the temporal range of the selected data 
4. Two new cards to the left of the main data selection card: (1) How to use this panel and (2) Current selections 
5. The time slice is now highlighted in **grey**. This is the reverse of the previous behavior, when the selected time slice was shown as **white** and the not selected time slice was shown as grey. For me personally, this is more clear. 
6. Area average option is now grouped with location subsetting. …
> Modernizing app.select & adding utilities/forecast zone subset options

- climakitae/meteo_yr.py
- climakitae/selectors.py
Quick fix to address the map offset issue with the little location subset map. 
**To test:** Please try pulling up the following GUIs to ensure that the location subsetting map (see below) is in a reasonable location for all the panels. Thanks!
> Fix messed up map offset for location.view

- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/derive_variables.py
- climakitae/meteo_yr.py
- climakitae/selectors.py
- climakitae/utils.py
- climakitae/view.py
This PR pulls some generalized function (such as finding the closest grid cell to a coordinate pair, and computing HDD and CDD) into the climakitae library. I've also added a function that reads and loads catalog data from a config csv file, as demoed in the intro notebook for the DFO. Lastly, I modified the heatmap function in the meteo_yr library so that a default colormap is applied. This update fixes the unit issue we all noticed when running the DFO notebooks on Thur Jan 6. 
**To test:** Just look through the climakitae code changes, and run through the INTRO notebook, available [here](https://github.com/cal-adapt/cae-examples/blob/dfo_notebooks_clean/specific_use_cases/demand_forecast_office/INTRO_annual_consumption_model.ipynb)
> Changes related to the DFO notebooks

- climakitae/threshold_tools.py
- climakitae/visualize.py
for [Threshold basics notebook update PR in cae-examples](https://github.com/cal-adapt/cae-examples/pull/39)
- label color bars with variable name and unit (if any)
- correct variable units in hover tooltips
- match plot title language with that elsewhere in the notebooks
- split plot titles into 2 lines to not have them cut off
- add variable unit to relevant plot titles
> Update plots for threshold basics and application notebooks

- climakitae/data_loaders.py
- climakitae/selectors.py
- climakitae/threshold_tools.py
- climakitae/view.py
- tests/threshold_tools/test_thresholds_exceedance.py
- tests/threshold_tools/test_thresholds_returns.py
GitHub actions is pulling new Black 23.1.0 (previously 22.10.0) version, so code needs to be reformatted.
> Formatted to new Black 23.1.0 Version

- climakitae/core.py
- climakitae/data_loaders.py
core.py was importing the wrong function name. Not sure how I missed this! Hopefully this solves the issue.
> Fix bug in retrieve_from_csv

- climakitae/meteo_yr.py
Updates in less than a minute on my laptop, with no dask cluster, fwiw.
> Removed for loop to speed up AMY.

- climakitae/meteo_yr.py
- climakitae/selectors.py
- climakitae/threshold_panel.py
- climakitae/timeseriestools.py
- climakitae/warming_levels.py
This PR replaces ObjectSelector with Selector for Param widgets.
> Replace ObjectSelector with Selector

- climakitae/data_loaders.py
This PR expands the spatial domain that is retrieved when grabbing the Oakland Airport and/or SFO Airport weather stations. It forces the retrieval of the entire model domain, then subsets, such that the gridcells in the water of the bay are included. Ideally we should modify all shapefiles that have gridcells in the bay area to include the water areas, but this fix is fine for now. 
**To test**: Make sure data retrieval at the OAK and SFO stations work.
> Bug fix for bay area stations

- climakitae/meteo_yr.py
Fix AMY panel so that it responds dynamically to selections to adapt height to whatever is selected. 
**To test**: Mess around with the app.explore.amy() panel. Change around the options, make sure the panel doesn't overextend the borders at any point.
> Fix AMY panel height

- climakitae/selectors.py
In my last PR, I accidentally deleted a few lines of code that generate one of the figures in app.select.
> Add back in code I accidentally deleted 

- climakitae/data_loaders.py
This fixes a bug in the station selection code by adding back in the grid_mapping attr, which I had unknowingly removed.
**To test**: Ensure that retrieval and loading of weather station data works using ``app.select()`` and ``app.retrieve()``.
> Fix bug in station selection

- climakitae/core.py
- climakitae/explore.py
- climakitae/meteo_yr.py
- climakitae/selectors.py
- climakitae/warming_levels.py
This PR removes global variables from all modules. 
**To test**: Just play around with climakitae (i.e. `app.select()`, `app.view()`, `app.explore...`) and make sure you don't find any weird bugs. 
Edit April 28: I fixed the warming levels bug and this PR is good to review now :D
> Remove global variables from modules

- climakitae/core.py
Remove the tmp directory from the catalog path in climakitae core.py
> Remove reference to temp directory in AE bucket

- climakitae/data/variable_descriptions.csv
- climakitae/data_loaders.py
Add new LOCA2 variables to climakitae: min relative humidity, max relative humidity, solar radiation at the surface, and windspeed. 
REQUEST: I need an extended description for solar radiation at the surface (rsds). Can a scientist help me think of a good, longer description of this variable? 
**To test**: Try retrieving the new variables (Only shown if you've checked "Statistical"-- and ONLY "Statistical"!)
> Add new loca2 variables

- climakitae/unit_conversions.py
I'm developing some wildfire indices and need windspeed in miles per hour, so I figured I'd add it as a unit conversion option since it's not one already. 
I also deleted a redundant repeat code line. 
**To test**: Confirm that the wind speed in mph looks right.
> Add mph conversion for wind speed

- .github/workflows/ci.yaml
- climakitae/data_loaders.py
Added descriptive code comments and removed legacy code from past average meteorological year related things.
> Clean up franken-loop in data_loaders.py

- .github/workflows/ci.yaml
This PR removes Mamba from the conda build environment. Seems to solve the Win-64 caching issue.
> New CONDA Workflow

- climakitae/data_export.py
- warn and name unnamed DataArrays so that they can be exported
- rename columns to ease column access in R (no spaces / special characters, start with a letter or a dot, unique)
- add DataArray variable unit to header if it exists as the `units` attribute
- warn about Excel column limit in addition to row limit
To test: export data in notebooks with export sections.
> Add features to CSV export

- climakitae/uncertain_utils.py
This PR fixes broken uncertainity utils function. Uncertainity utils calls a renamed function in data_loaders that does not exist anymore.
> Fix uncertainity utils renamed function call

- climakitae/derive_variables.py
Our derivation was resulting in some really low RH values. RH for CA doesn't go below 0.8. We set the limit here to 0.5. 
**To test:** Try retrieving the relative humidity data. Make sure it looks appropriate.
> Limit relative humidity to < 0.5%

- climakitae/data_loaders.py
- climakitae/derive_variables.py
- climakitae/indices.py
- climakitae/unit_conversions.py
Nicole and I noticed some unrealistically, and quantitatively incorrect, high relative humidity values in several applications (AMY; heat index). This PR switches the equation used to address this, as well as sets lower (0.5) and upper (100) limits on the relative humidity results.
To test, retrieve RH and ensure that values look good
> Switches the relative humidity equation

- climakitae/warming_levels.py
This allows the user to customize the time window they want to generate around the warming levels date. The default is set to 15 years, so no changes are to be expected in the existing functionality. 
Make sure the function `get_anomaly_data` works as expected, using the `windows` argument to test that the window changes.
> Add window as optional argument for warming_levels

- climakitae/indices.py
Update to better match documentation
> Small fix to heat index derivation to better match NCAR documentation

- climakitae/view.py
- climakitae/warming_levels.py
This PR fixes bug that affected warming levels because of change to variable descriptions.
> Fix timescale for daily, monthly

- docs/README.md
Instruct developers to run `make serve-docs` from root `climakitae` directory
> Update README.md for building docs

- docs/climakitae.rst
- docs/data.rst
A couple typo fixes, and one additional note about which selectors accept multiple values
> Edits to 'working with data' page in readthedocs

- climakitae/core/data_interface.py
- climakitae/core/data_load.py
I think this is all that is needed. I am able to select and retrieve the derived vars. I did notice that `ck.view` returns a blank map for these data though. I am not sure if this was an issue before or if I have missed something?
> Readd variable_type to select panel

- climakitae/data/hadisd_stations.csv
Updates the station names in the hadisd_stations.csv to include their ICAO as well as removing the / character in two of the new stations
> Update HadISD station names

- climakitae/util/utils.py
1. Modifies the existing `compute_multimodel_stats` to include the multi-model median.
2. Modifies the existing `trendline` to provide an option to calculate the trendline either via the mean or median
3. Includes a new summary table function
> Heat Index NB: helper functions

- docs/contribute.rst
I added a draft of some text to populate the Contributor Guidelines page of the readthedocs documentation. To review, follow the instructions in `docs/README` to build the documentation locally and view in your browser. 
I'm open to suggestions on content/formatting/etc.!
> contributor guidelines draft

- climakitae/explore/warming.py
**Back-end changes to Updated GWL notebook**
Making changes to GWL framework updated notebook. Main changes include separating warming levels individually, so that data could be properly sliced into different 30-year chunks in `sliced_data`.
To test, please run the corresponding `updated_warming_levels.ipynb` from cae-notebooks.
> GWL Upgrade

- climakitae/util/generate_gwl_tables.py
Debugging WL generation to allow for warming levels to be generated at a more granular level (0.5 vs 0.01). Fixes the bug of timestamps jumping to abnormal warming levels.
> WL Generation Debug

- climakitae/explore/agnostic.py
- climakitae/explore/threshold_tools.py
- climakitae/util/utils.py
PR to address comments left for `agnostic` tools PR and to add proper documentation and linting to LOCA simulation finder tool.
> `agnostic` tools PR comments review

- climakitae/explore/agnostic.py
This PR rewrites the LOCA exploration tool in `agnostic.py` to be much more concise and readable in the codebase while also integrating changes for PGE/SCE support for custom arguments passed in (i.e. years, months, metric).
This can be tested with new `cae-notebooks` PR here: https://github.com/cal-adapt/cae-notebooks/pull/89
> Agnostic Tools- LOCA exploration tool complete rewrite and custom functionality added

- docs/requirements.txt
Update `Sphinx` packages in documents `requirements.txt` file:
Sphinx 7.2.6
sphinx_book_theme 1.1.0
sphinx_design 0.5.0
> Update Sphinx version for readthedocs

- docs/requirements.txt
- requirements.txt
This PR moves the Sphinx required packages to the docs requirements.txt file.
> Move Sphinx required packages to docs/req.txt

- climakitae/core/data_export.py
THIS IS A CLEAN VERSION OF APPROVED PR #327 
- In fixing an issue in #327, the branch diverged too far from main. Was reset back to an older commit and fixed. 
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes
> Bug fix on TMY export for dataframe size -- clean

- climakitae/explore/agnostic.py
Generalizing agnostic tools to handle WRF data as well.
We want to visualize WRF data, and have the option to select 1 or more specific simulations, so we need to generalize existing code (agnostic tools) in order to do so.
None
None
Running `agnostic_tools.ipynb` with code changes and confirming that WRF data is indeed extracted.
> Generalizing agnostic tools to include WRF

- climakitae/explore/agnostic.py
Fixing small issue in `agnostic.py` to address getting the closest gridcell with LOCA data.
Tool 2 of agnostic tools for finding a specific gridcell does not work with LOCA data.
> Fixing small bug with finding nearest gridcell for LOCA

- climakitae/core/data_load.py
Quick PR to cleanup removed ProgressBar import
> Remove ProgressBar import

- climakitae/core/data_load.py
Switch back to using `xr.compute` in `ck.load` as it makes more sense and seems to take less spike memory.
> Switch xr.load to xr.compute in ck.load

- climakitae/core/data_load.py
- climakitae/explore/vulnerability.py
This code has been developed as a pilot function for SCE's CAVA analysis. 
This code in `vulnerability.py` allows the user to pass in a series of parameters into the `cava_data` function and grab the desired data in its raw form or once a metric and threshold are applied to it.
This is needed as an initial step for a versatile function for SCE (and future IOUs) to use for their CAVA analyses, and potentially be turned into an API to be used in the future.
> SCE CAVA Pilot Phase 1

- climakitae/explore/warming.py
Currently, the `warming_levels.ipynb` notebook is breaking due to the fact that are no WRF simulations that reach 4 degrees warming (a small win for the world). This PR addresses this bug by creating conditional statements for if/when there are no simulations that reach a certain degree of warming.
We want to still use warming levels and warming levels visualizations even if no simulations reach a certain degree of warming.
We want our notebooks to run properly.
Ran through `warming_levels.ipynb`
> Debugging WL for WRF simulation 4 degree case

- climakitae/core/data_load.py
This fixes a reference to old "Application" object.
> Fix documentation

- climakitae/explore/vulnerability.py
- climakitae/explore/vulnerability_table.py
This includes code that iteratively calls on cava_data with a series of parameters to generate the CAVA pilot table from SCE. Front-end code is in https://github.com/cal-adapt/cae-notebooks/pull/111 . 
We want a table generated to see the full functionality / potential of cava_data function.
> CAVA Pilot Table Generation

- climakitae/data/variable_descriptions.csv
This PR enables the `swddir` variable `"Shortwave surface downward direct irradiance"` in the `ck.Select` GUI.
> Turn swddir variable on in GUI

- climakitae/data/variable_descriptions.csv
Previous description of the "Instantaneous downwelling shortwave flux at bottom" variable was noted to be confusing. This pushes a simple update to the long description to clarify, and matches the appropriate statistical matching variable description as well.  
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] Any dependent changes have been …
> clarify ghi / swdnb description to match

- climakitae/core/data_load.py
- climakitae/util/unit_conversions.py
Fixes bug in monthly precip unit conversions. I had to change some logic in core/data_load.py... I am hoping I didn't introduce any new bugs, and tested this myself, but could use some careful review on the units here. 
n/a
- [n/a] I have added tests that prove my fix is effective or that my feature works
> Precip units fix

- climakitae/util/utils.py
For several tools in our codebase (and for many external library calculations), there is a need for a dimension named `time` in a given DataArray for calculations. However, warming levels code removes this time index and replaces it with a `hours/days/months_from_center` dimension, since that is more accurate name than just `time`. This also does create some challenges with computing on this DataArray, since the `hours/days/months_from_center` dimension is filled with timedeltas and no longer timestamps. So, this PR is focused on including a helper function in `utils` that allows a user to toggle from WL indexing to a dummy time-based indexing to allow for potential metric calculations to still occur as desired.
This function is aimed to be used in …
> Adding dummy time index conversion function for warming levels

- docs/climakitae.explore.rst
- Remove duplicate documentation of timeseries and uncertainty modules
- Switch them to two newly developed modules (vulnerability and vulnerability_table)
Fix issues on this page https://climakitae.readthedocs.io/en/latest/climakitae.explore.html
Build succeeded. Preview: https://climakitae--382.org.readthedocs.build/en/382/climakitae.explore.html#module-climakitae.explore.vulnerability
- [not relevant] I have commented my code, particularly in hard-to-understand areas
- [not relevant] I have made corresponding changes to the documentation
- [not relevant] New and existing unit tests pass locally with my …
> Fix climakitae.explore documentation

- climakitae/explore/warming.py
> Adding line for cmap for max air temp at 2m

- climakitae/explore/vulnerability.py
As a part of Phase 2 Goal 3, we are working to include Historical Reconstruction data as an available option for `cava_data` function. In order to do so, we must validate the inputs (year range, ignore SSPs) to do so.
> Phase 2 Goal 3 - Adding Validation for using Historical Reconstruction Data

- climakitae/explore/vulnerability.py
- climakitae/explore/warming.py
This PR includes LOCA2 data as an available option for a warming levels approach for the `cava_data` function.
For phase 2 goal 4 of SCE pilot development.
> Phase 2 Goal 4 - WL LOCA Integration

- climakitae/util/utils.py
This PR includes/removes simulations depending on the dataset timescale as well as the resolution, rather than originally just the resolution.
WL notebooks
> Adding logic to `drop_invalid_wrf_sims` to account for difference in number of simulations by timescale too

- climakitae/explore/vulnerability.py
- climakitae/explore/vulnerability_table.py
- climakitae/tools/batch.py
- climakitae/tools/derived_variables.py
Working on incorporating batch mode into the SCE pilot, first with a time-based approach.
We want to decrease the runtime of running `cava_data` on a series of points.
With and without the `batch_mode` toggle.
> SCE Pilot- Batch Mode with a Time-Based Approach

- climakitae/core/boundaries.py
- climakitae/core/data_export.py
- climakitae/core/data_interface.py
- climakitae/core/data_load.py
- climakitae/core/data_view.py
- climakitae/util/cluster.py
- climakitae/util/dev_logging.py
- docs/climakitae.core.rst
Documentation updates pulled from refactor phase 2.
Fleshes out the core and util modules with more documentation.
- [ x ] This change requires a documentation update ;)
Not tested...
- [ x ] I have made corresponding changes to the documentation
> Documentation Update pulled from Refactor #2

- climakitae/explore/vulnerability.py
Small changes added to SCE pilot.
1. Change “off-ramp” to “raw”
2. Add in option to change distribution in 1-in-X events
3. Default of `mm` for precip, `degF` for heat index and temp events.
Unit validation **not** added yet, will coordinate with Nicole on the best way to do this.
> Small Changes to Upgrade SCE Pilot

- climakitae/explore/vulnerability.py
- climakitae/tools/batch.py
- climakitae/util/utils.py
Including parameter validation for SCE pilot. This should make the code more readable. Additionally, `cava_data` now catches multiple logic errors at once, allowing the user to fix multiple issues at once rather than fixing them one by one. 
WIP: Catching multiple input validation errors at once. I.e. inputting `meannn` for `metric_calc` and `Dynamicallll` for `downscaling_method` will only show the `meannn` as an issue. Once that is addressed, then it shows `Dynamicallll` as an issue.
> Including param validation for SCE pilot

- climakitae/explore/warming.py
Follow up from PR #407, this PR cleans up the second panel in the warming levels visualization. Once this is approved, I will merge both branches :D
> Fix up the second panel in WL notebook

- climakitae/core/data_interface.py
Enable users to select variables not shown in the GUI, but that exist in the variable_descriptions.csv file under show=False. 
How to select hidden vars: 
```
selections.enable_hidden_vars = True
selections.variable = "Surface runoff" 
```
> enable hidden var selection

- climakitae/util/utils.py
The original implementation was more hardcoded because I couldn't find a clear, succinct way to implement this WRF WL simulation filter. But now with new data coming in and new util functions, this solution is more succinct, readable, and capable of being flexible with different numbers of simulations coming in.
Needing to change the WRF WL filtering method to work properly again.
Manually testing
> Upgrading WRF WL Simulation Filter

- README.md
- docs/data.rst
- docs/index.rst
- Fix references to removed visualization/GUI features on the [Working with our Data](https://climakitae--422.org.readthedocs.build/en/422/data.html) page. 
- Update them to climakitaegui equivalents.
- To reflect changes in the [code split](https://github.com/cal-adapt/climakitae/pull/408) on Read The Docs
Build succeeded. Preview: https://climakitae--422.org.readthedocs.build/
- [not relevant] I have commented my code, particularly in hard-to-understand areas
- [not relevant] I have made corresponding changes to the documentation
- [not relevant] New and existing unit tests pass locally with my changes
- …
> Correct documentation of visualization/GUI features

- climakitae/explore/vulnerability.py
Didn't define `one_da` for Air Temp case for 1 in X. Fixing that in this PR.
> Quick fix bug with UnboundLocalError

- climakitae/core/data_interface.py
> add documentation

- climakitae/util/generate_gwl_tables.py
Reviewed `generate_gwl_tables.py` and made code more readable in certain locations.
We needed to document the GWL year generation process and make it more interpretable by developers.
<br>
> Improve readability of `generate_gwl_tables.py`

- climakitae/explore/vulnerability.py
Quick fix to deal with batch mode error in CAVA function.
Variable was erroneously changed before. Should be fixed now.
<br>
> Fixing Error in Batch Mode CAVA

- climakitae/explore/vulnerability.py
Mainly for testing purposes to get more lat/lons than just the ~32 station ones.
<br>
> Sticking util func in vul.py to grab lat/lons of all SCE service territory points

- climakitae/explore/vulnerability.py
Reverts cal-adapt/climakitae#442 because LOCA batch mode doesn't still doesn't work
> Revert "SCE Pilot- Upgrading CAVA pilot to focus on batch mode to reduce code complexity"

- climakitae/explore/vulnerability.py
Adding BA-model filtering for time-based WRF batch mode
Need this because it doesn't currently exist
<br>
> Separately add BA model filtering to time-based batch mode for WRF

- environment.yml
- setup.cfg
This PR updates setup.cfg and environment.yml files to reflect adding Xarray io optional dependencies and making sure env.yml is up-to-date.
<br>
> Added Xarray io deps to setup and env.yml

- climakitae/core/data_interface.py
- climakitae/core/data_load.py
- climakitae/util/utils.py
Big improvements to the ``get_data()`` function to enable retrieving data manually using a warming levels approach. I also added an option to set the time slice. I changed some of the logic in the function as well to be better organized.
Try using the ``get_data()`` function to pull data using a warming levels approach. Use a bunch of different options; see what breaks, and if the error message for a bad input is helpful. **PLEASE TELL ME WHAT YOUR FUNCTION INPUTS ARE IF YOU FIND AN ERROR I NEED TO FIX SO THAT I CAN REPRODUCE IT!!** 
For example: 
```
get_data(
variable = "Precipitation", 
downscaling_method = "Dynamical", 
resolution = "45 km", 
timescale = "monthly",
#time_slice = (1800,1900),
#scenario = "Historical Climate",
approach = "Warming lEvel",
warming_level_window = 10, …
```
> Improvements to get_data() function to enable pulling data without GUI

- climakitae/explore/warming.py
Print "a simulation" when `sliced.simulation[0]` errors
<br>
> Handle error in a user warning in `warming.py`

- climakitae/explore/warming.py
- climakitae/util/warming_levels.py
> Changing other function names

- tests/conftest.py
- tests/create_test_dataset.py
- tests/create_test_dataset_hourly.py
- tests/data_interface/test_variable_descriptions_csv.py
- tests/data_load/test_sim_dimension.py
- tests/data_load/test_unit_error.py
- tests/derived_variables/test_derived_variables.py
- tests/indices/test_indices.py
- tests/threshold_tools/test_thresholds_exceedance.py
- tests/threshold_tools/test_thresholds_returns.py
- tests/timeseriestools/test_timeseriestools_monthly.py
- tests/vulnerability/test_vulnerability.py
This PR removes unused package imports in tests and reorders package order in files.
Simply removes unneeded imports.
> Cleanup test imports

- docs/conf.py
Simply changes the software version that was missed in the doc conf
Missed file in last release
[How should reviewers test the changes?] 
- [ x ] This change requires a documentation update
> Update missed doc version

- climakitae/core/data_load.py
- climakitae/explore/timeseries.py
- climakitae/explore/vulnerability.py
- tests/threshold_tools/test_thresholds_exceedance.py
This fixes deprecation warnings called out by tests. It is not exhaustive. 
Keep up with dependent package changes as they are presented to us.
Deprecation warnings disappear from test results. Some deprecations warnings are in 3rd party software and hopefully will be addressed as their code is updated.
> Fix deprecated calls in code

- climakitae/util/logger.py
- tests/util/test_logger.py
Test coverage for `util.logger` up to 100%
Test coverage is important for good code hygiene.
```bash
pytest tests/util/test_logger.py --cov=climakitae.util.logger --cov-report term-missing
```
> Test coverage for `climakitae.util.logger`

- .github/workflows/ci.yaml
Trying to figure out when we can trigger Advanced Testing on main pushes. I will quickly merge this and may need to do other quick merges as main push needs to happen to test
Main branch not running all tests.
Need to merge to see if logic works.
> Main Testing Logic Fix

- climakitae/explore/threshold_tools.py
[How should reviewers test the changes?]
> Adding small print change to bms drop warning

- climakitae/explore/threshold_tools.py
[How should reviewers test the changes?]
> Fixing small typo with bms error msg

- README.md
I've updated the README to be a little more modern. Happy to workshop the language.
The README was old and wasn't particularly informative of how to get `climakitae` installed and working. Hopefully this starts to alleviate some of those issues.
Take a look at the readme [here](https://github.com/cal-adapt/climakitae/tree/improve/readme). Make sure all the links work. Make sure the language looks fine.
> Improve and modernize `climakitae` README

- climakitae/tools/indices.py
This PR add additional information about the heat index calculation to the docstring.
We want to provide more information about the purpose of this function.
No functional code changes. Read docstring and suggest changes as needed.
> Add text to heat index docstring

- .github/workflows/ci-main.yml
- README.md
Reverts cal-adapt/climakitae#600
> Revert "update main workflow and README"

- climakitae/explore/vulnerability.py
- setup.cfg
Changed default initialization values to ensure that tests run correctly.
Tests need to run.
Check that advanced tests run correctly
> Fixing tests

- .coveragerc
- .github/workflows/ci-main.yml
- .github/workflows/ci-not-main.yml
- climakitae/new_core/data_access/__init__.py
- tests/__init__.py
- tests/new_core/__init__.py
- tests/new_core/test_user_interface.py
- tests/uncertainty/__init__.py
Adding tests for new core UI: 85% coverage
Always good to have tests
1) validate that all ci tests ran successfully
2) `python -m pytest tests/new_core/test_user_interface.py --cov=climakitae -v`
> Test/new core UI

- .github/pull_request_template.md
Add a new tests bullet point to the pull request template.
Thought it might be useful since this bullet is missing currently.
See if you like the new bullet point
> Add new tests bullet point to `pull_request_template.md`
