cal-adapt/climakitae

- climakitae/data_loaders.py
- climakitae/selectors.py
Doing a minor PR here, just so I can have this for my ongoing testing.
- Changes default lat/lon box location (CA) and display (just an outline)
- adds a checkbox to 'append historical' so that the historical climate simulation and each of it's corresponding SSPs are appended as one variable with a longer time dimension
- adds a checkbox to 'area average', so that the area selected is averaged spatially to return a timeseries
> Timeseriestools

- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/selectors.py
This PR addresses:
- fixes a bug when scenarios with different time dimension ranges are both selected
- fixes an issue in which the original metadata was lost in 'generate'
- curates the WRF variable list
- adds a "Precipitation (total)" option that is the sum of RAINC + RAINNC
- renames 'generate' as 'retrieve' (in core.py)
> Generate fixes

- requirements.txt
- setup.cfg
This adds dependencies on intake-xarray and s3fs which are required for reading the Zarr stores from the intake catalog. It also pins the packages to the versions tested against on the container image.
> Add missing deps and pin package versions

- climakitae/data_loaders.py
- climakitae/selectors.py
- Fixes:
-  a bug caused by a mis-typed variable in an assert in data_loaders.py
- scenario options no longer reset to eliminate 'Historical Climate' when you select 'Append historical'
- Adds the following to the 'select' panel:
- Visualization of selected scenarios on a timeline 
- Time-slicing functionality
- If the user selects a time-slice for which there is zero data, an assert error points this out when they call 'retrieve' 
- Shows bounds of WRF domains on area selection map
- Makes moving between different kinds of area-selection more intuitive:
- If you change the lat/lon sliders, changes area_subset to lat/lon
- If you change the cached_area selection, changes area_subset to appropriate type
> Select fixes

- climakitae/selectors.py
This fixes the 400 bad request thrown by the US Census ArcGIS Server by adding quotes to the state query which was being parsed as an integer type instead of a string. This was likely due to an ArcGIS Server update which now treats these query parameters differently as it was working previously.
> Fix census county url

- climakitae/threshold_tools.py
- climakitae/visualize.py
added confidence intervals to threshold_tools functions
updates:
- added new function "bootstrap"
- added bootstrap capabilities to "return_value", "return_prob", and "return_period" capabilities
- changed ValueError exceptions to also include ZeroDivisionError (_note: this does not impact calculations but removes an error that would occur with the gumbel distribution and instead outputs an np.nan for that gridcell if either of these two errors occurs_).
- ran black for formatting
> confidence intervals for threshold_tools

- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/selectors.py
The primary purpose of this PR is to speed up the import of climakitae. It achieves this by:
- delaying the reading of the catalog to the call to ck.Application()
- delaying the reading of area-selection shapefiles to ck.Application()
As a result, ck.Application() is slower to execute, but climakitae imports immediately, as one might expect it to.
This was accomplished by learning to pass parameter values to classes that inherit from param.Parameterized, and adding an __init__ on top of the inherited one from the metaclass for both DataSelector and LocSelectorArea classes in selectors.py. 
Then the resulting changes in core.py and data_loaders.py were brought into agreement with the new data organization. The catalog is read in core.py now, and a get_catalog_contents function was added …
> Dynamically populate param classes

- climakitae/data_loaders.py
This PR reprojects the Watershed shape selected from GUI from Pseudo Mercator to WGS84 to be compatible with the other boundary files used.
I have tested this on the HUB. I picked the "Carrizo Plain" watershed and works fine for 3km and 9km, but the 45km returns the "Insufficient Gridcells" assertion. I guess that is because the watershed is in 1 cell and not getting the centroid? Or some similar behavior (not majority?). Is this the behavior we want or should we work on having it return any cells it intersects instead?
Please test this in your own environments as well. Thanks.
> Reproject watershed polygon to WGS84 before regionmask

- climakitae/data_loaders.py
- climakitae/selectors.py
This PR tackles replacing the current boundary data with parquet files based within an intake catalog on CA:AE S3 bucket. It modifies `selectors.py` and `data_loaders.py`. In selectors in replaces the Boundary data refs with the S3 parquet files and redos how the states dictionary is created removing regionmask and numpy as dependencies. The watersheds dataset also switches to using the index instead of the objectid as a primary key. This is so ALL subset area types can be handled in a similar way and the code compacted into a function call and logic streamlined. The same treatment of code compacting and streamlining is done in `data_loaders` and logic is same as in `selectors`.
> Use S3 based parquet files to run subsetting plus code streamlining and cleanup

- climakitae/data_loaders.py
- climakitae/selectors.py
- environment.yml
- requirements.txt
This PR completely removes all dependency on `regionmask` by replacing the remaining calls with `rioxarray.clip`. This particular code is dependent on the changes in #63. `_read_from_catalog` now passes a geometry collection instead of a Region object to `_open_and_concat` where the mask is done with one command! It appears to work just as before and I have not seen much difference in performance, which is unfortunate but at least we have one less non-pangeo dependency.
It seems to fail gracefully without the "Insufficient Gridcells" assertion. When I query for the 3km data with Washington state which is non-intersecting I get: `NoDataInBounds: No data found in bounds. Data variable: T2` from `rioxarray`. We could enhance this change by adding some custom error handling for this.
> Replace regionmask with rioxarray.clip for masking of data

- climakitae/core.py
- climakitae/utils.py
- climakitae/view.py
This new feature is designed to allow the user a quick glance at their selected data. It generates a map for data with spatial coordinates, and a line plot for data with only a time coordinate. 
At the moment it only works for DataArrays, but we could later add functionality to work with Datasets if we envision that as a part of our workflow. 
**Examples (screenshots) of the new feature is at the bottom!**
As an example, the steps to call app.view() from the getting_started notebook would be: 
`app.select()`
`data = app.retrieve()`
`data = data.compute()`
`app.view(data) `
You don't _need_ to call `data.compute()` beforehand, but `app.view()` is quite slow without it. Thus, I've set up the code to raise a warning if you try to pass it a zarr store. It will still generate a map/plot, just …
> New feature: app.view()

- climakitae/derive_variables.py
**Information:** The grid_mapping attribute is lost for some reason by the metpy function that computes relative humidity in our derive_variables module. This is causing issues with reprojecting the data, as grid_mapping is used by rioxarray to determine information about the data's CRS. In this PR, I just add back in that attribute. 
**To test:** Try just selecting relative humidity from app.select() and make sure the attribute "grid_mapping" appears.
> Add back in grid_mapping attribute for relative humidity

- climakitae/data_export.py
- The export() function now assumes that users have subsetted and sliced their data array already (ie, it accepts no arguments to do so).
- It will only accept multi-variate datasets for exporting to netcdf (not to csv or geotiff).
- It is no longer writing out a metadata txt file for csv or geotiff.
- Output netcdfs still violate CF conventions by setting _FillValue to NaN for coordinates - this is xarray default behavior.
- Raises an error if a file with the same name exists in the workspace.
> Simplified export

- environment.yml
This PR will hopefully fix the broken test environment. `intake` was updated to `0.6.6` and since it wasn't pinned this was used by the runners in the github workflow. It is incompatible with the version of `intake_xarray` installed.
> Pin intake to 0.6.4 in environmental.yml

- environment.yml
- requirements.txt
- setup.cfg
This PR updates the `environment.yml` file used by the testing environment to the package versions currently on the CA:AE HUB server. Also removes `black` and `flake8` as they are not used at this time.
Also updates `requirements.txt` to match `environments.yml`
> Update environment.yml file to current HUB package versions

- environment.yml
I have 2 equal signs for a package version and that is not the right format for this file
> Fix typo in environment.yml file

- environment.yml
- requirements.txt
- setup.cfg
Here are some minor packaging and dependency changes that remove a duplicate `lmoments3`, a non-existent `proj`, and separate testing from runtime deps.
> Clean up package dependencies

- climakitae/data_export.py
- adds global data array attributes as raster tags when exporting to GeoTIFF
- addresses various dimensionality issues:
- GeoTIFFs can have a max of 3 dimensions and require both x and y dimensions
- Allows z dimension to be time, simulation, or scenario and prints information accordingly 
- Squeezes non-spatial singleton dimensions while retaining coordinate information (eg, which simulation was sampled) as possible
To test:
1. Export a data array (not a dataset - unless you want to test the error message thrown) as GeoTIFF.
-   Have some fun with it. Leave as many dimensions as you want, of whatever length you want. This will help test out the error codes! 
2. Then load the resulting .tif into the notebook and check the tags:
`import rasterio`
`ds = rasterio.open('file_name.tif')` …
> geotiff export refinement

- climakitae/warming_levels.py
The reprojection code chunk in app.explore.warming_levels() uses a ton of memory, causing the kernel to fail when you play with `app.explore.warming_levels()` (no bueno!!). 
I've commented out this reprojection code. This seems to solve this issue. The explore.warming_levels panel now uses ~1.6GB of memory, instead of ~3.5GB before removing the reprojection code. 
**To test:** Just call app.explore.warming_levels(). Play around with it. Make sure it doesn't crash your kernel. Try running the entire warming_levels notebook from cae-notebooks, **making sure you replace app.explore() with app.explore.warming_levels()**
> Remove reprojection from app.explore() to avoid overloading memory

- climakitae/warming_levels.py
Simple PR to switch the colormap for relative humidity **only*** in warming_levels, because it has both positive and negative values. 
**Caveat**: If/when the warming_levels introduces more variables than just air temperature and relative humidity, a more extensive anomaly colormap setting will need to be in place. All variables have a default colormap in the descriptions csv, however this _should_ be overridden when an anomaly is calculated to display a diverging colormap instead. Midpoint normalizing may need to occur then: https://discourse.holoviz.org/t/diverging-colorbar-around-asymetric-data/3339
To test this, just look at relative humidity in app.explore.warming_levels() and make sure that its the diverging colormap instead of its preset blues.
> Switch RH colormap for warming_levels

- climakitae/tmy.py
This PR works explicitly for in-notebook features for the Average Meteorological year notebook: https://github.com/cal-adapt/cae-examples/blob/typical_meteorological_year/explore_amy.ipynb
Effectively: the two critical AMY functions **tmy_calc** and **remove_repeats** were pulled out of the class so that they could be calleable in-notebook for analyzing/plotting a diurnal cycle, an annual cycle, and export functionality of the AMY dataframe itself. Some of the dataframe transforms were therefore included and cleaned up in the larger script. 
**Note**: Exporting the AMY dataframe _currently_ does not conform to our existing export functionality, so there is a separate in line call for that. Exporting the relevant catalog data works as desired. 
To test this: please run through the …
> Fine-tuning on AMY for diurnal cycles + export

- climakitae/warming_levels.py
This is a simple fix for #98 by setting the new Xarray DataSet created attributes to the attributes of the input DataArray. @vicford Can you check if all these attrs are appropriate to keep in the output data. If not we can pop out those ones.
> Copy input attrs to output data in get_anomaly_data

- climakitae/tmy.py
Quick fix for Issue https://github.com/cal-adapt/climakitae/issues/109
Just moves the toolbar statement into a single .opts() call with minor whitespace cleaning
To test: 
Just make sure that the AMY heatmap in explore_amy notebook (or by calling app.explore.amy) works as desired.
> Cleans up toolbar options for AMY heatmap

- climakitae/catalog_convert.py
- climakitae/data_loaders.py
- climakitae/selectors.py
- climakitae/threshold_panel.py
- climakitae/tmy.py
- climakitae/utils.py
- climakitae/view.py
- setup.cfg
This PR addresses some small comments from reviewers on the main catalog restructure PR. 
1. Rename `catalog_utils.py` to `catalog_convert.py` 
2. Add a space between the resolution options; i.e. "45km" --> "45 km" 
3. Rename the functions within `catalog_convert.py` to be more descriptive 
4. Add back in an error statement if the user has selected "Append Historical" but no SSP 
5. Rename `selections.dataset` to `selections.downscaling_method`
6. Avoid creating large dask chunks and silence warning. This is done by setting the following config at the top of `data_loaders.py`:  ```dask.config.set({"array.slicing.split_large_chunks": True})```
7. Fix a small bug in `app.view`
> Small catalog fixes 

- climakitae/data_loaders.py
This should hopefully fix the cluster killed worker issue in the catalog_restructure branch
**To test:** Try running this in the AE hub with a cluster. Code for spinning up a cluster is below. 
```
from dask_gateway import GatewayCluster
cluster = GatewayCluster()
client = cluster.get_client()
cluster.scale(8)
```
> Remove preprocessing function from data loading

- climakitae/threshold_panel.py
This PR addresses an [issue that Eric raised](https://github.com/cal-adapt/climakitae/issues/107) that there are two return lines in one of the functions in threshold_panels.py. I just deleted the redundant one.
> Remove redundant return line in threshold_panel.py

- climakitae/timeseriestools.py
- tests/timeseriestools/test_timeseriestools_monthly.py
This PR addresses an [issue raised by Eric](https://github.com/cal-adapt/climakitae/issues/108) to replace the assert statements with error messages. I also improved the error messages. 
**To test:** Try running the timeseries_examples notebook and loading the wrong data. The following line should raise an error with an appropriate error message if you feed it "bad" data (i.e. data that can't be used by the timeseries tool) 
```
timeseries = tst.Timeseries(my_data)
```
> Timeseries assert --> error fix

- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/selectors.py
- climakitae/tmy.py
Just had to modify the code a bit to account for the ensemble mean data now being available in our main data catalog. This required me to add simulation as a parameter to app.select, such that app.explore.tmy could select for just the ensmean data, and app.select could ignore the ensmean data (and not return it as an additional simulation). 
I realize the explanation is a bit confusing. Feel free to add questions here for additional clarity and I will respond and try to clear up any confusion. 
**Once this PR is approved, I will merge it as the same time as the amy_cached_data branch**
**To test:** Just try running app.retrieve() for different datasets. Also try running app.explore.amy(). Thanks! 
_Note to self: Need to confirm that this doesn't cause any issues with the notebooks in …
> Rework code after ensmean data was added to main data catalog

- climakitae/data_loaders.py
- climakitae/explore.py
- climakitae/selectors.py
- climakitae/tmy.py
This PR adds a new function `app.explore.amy_selections()` that allows users to observe the settings in the AMY panel. Specifically, it returns the AverageMeteorologicalYear object generated in `app.explore.amy()`. I also renamed a few of the params in `tmy.py` to be more descriptive for the users' benefit. 
Workflow I recommend to get info from the amy panel: 
```
app.explore.amy()                                          # Pull up the panel
amy_selections = app.explore.amy_selections()              # Get AverageMeteorologicalYear object generated by amy panel
data_type = amy_selections.data_type                       # Absolute or Difference
computation_method = amy_selections.computation_method     # Warming Level Future or Historical
warmlevel = amy_selections.warmlevel …
```
> Add return function to allow users to observe selection options from AMY panel

- climakitae/metadata_update.py
This simple PR removes the hard coded `climakitae` version number from `metadata_update`. It is now set to whatever the version number is in `setup.cfg`.
> Set climakitae version dynamically in metadata_update

- climakitae/data_loaders.py
- climakitae/tmy.py
- climakitae/utils.py
This PR addresses quite a few changes to tmy.py. First, it changes the interactive heatmap generated by app.explore.amy() to a static matplotlib heatmap. This is because the hvplot heatmap was not allowing us control over the axes (see this bug report I raised in the hvplot GitHub [here](https://github.com/holoviz/hvplot/issues/975)). I also added a new function `lineplot_from_amy_data` in tmy.py, which is used in the new version of explore_amy(). Additionally, I added a function into utils.py that converts julian day into whatever string datetime format you want; this is used by `tmy_calc` now to improve readability of the data and plot axes. 
**To test:** Run through the version explore_amy.ipynb stored in the amy_usability_improvements branch of cae-notebooks (linked …
> AMY code updates to go with updates to explore_amy() notebook 

- climakitae/data_loaders.py
- climakitae/selectors.py
This simple PR replaces `assert` statements used in main code and replaces them with `raise` statements. The test logic is reversed to do this.
I left the `assert` statements in the test files as it seem appropriate there.
> Remove assert statements from main code and replace with raise error

- climakitae/cluster.py
The idea is to limit users to a single cluster instead of the default behavior of the `GatewayCluster` which always creates new clusters allowing a user to have multiple clusters running. This will attempt to reconnect to a cluster if one is available, and only create one if not.
Usage is the same as a `GatewayCluster`:
``` python
cluster = Cluster()
client = cluster.get_client()
cluster.shutdown()
```
> Limit users to a single cluster

- .github/workflows/ci.yaml
After reviewing the GitHub workflow documentation this looks like the best way to implement lint checking on the repo. With this workflow it didn't seem necessary for the other tests to be dependent on the lint. Also, this just checks the code and fails if not compliant. This would require the coder to run `black` before committing and pushing to pass the test. Or would we rather have the workflow reformat the code automatically? I'm not super sure how that would be done, but can look into it.
> Add Black lint checking to workflow

- climakitae/timeseriestools.py
Minor clarity improvement to the resampling "info one-liner" in the timeseries explore panel to better explain the resampling process.
> Timeseries resampling one-liner improve for clarity

- climakitae/data_loaders.py
This fixes a bug I found in `app.retrieve_from_csv()`, where a mysterious pandas error was being raised if any of the cells in a csv were unfilled. `pd.read_csv` was automatically setting these empty cells to NaN, which was causing issues down the line. Here, I set the empty cells to an empty string instead of NaN, which solves the issue! 
**How to review**: Just review the code change. No need to test anything out I think.
> Bug fix in app.retrieve_from_csv

- climakitae/core.py
- climakitae/meteo_yr.py
I had written a function a while back-- `retrieve_meteo_yr_data`-- that retrieves the necessary data for computing an average or severe meteorological year. But, for some reason, I put it in the meteo_yr module and had it accept `app` as an argument, which is pretty weird and unintuitive. 
In this PR, I just moved that function into core.py. This changed how the function can be used in a notebook. Because of that, I also had to change the DFU meteorological year notebook (see the related [cae-notebooks PR](https://github.com/cal-adapt/cae-notebooks/pull/33))
Current functionality: 
```
from climakitae.meteo_yr import retrieve_meteo_yr_data
data = retrieve_meteo_yr_data(app)
```
Desired functionality (this PR): 
```
data = app.retrieve_meteo_yr_data()
```
**How to review**: Try running the …
> Move meteorological year data retrieval function to core.py

- climakitae/utils.py
I identified a small error, in which the get_closest_gridcell function fails if given a lazily loaded dask array. I fixed this, and also slightly updated the documentation. 
**To test**: Just review the code here in GitHub. Nothing involved required unless you're feeling ambitious.
> Small change to closest gridcell function

- climakitae/uncertain_utils.py
- docs/api.rst
- environment.yml
I added the uncertainy utils to the climakitae API. I also added cmip6_preprocessing (a dependency of uncertain_utils) to our environment.yml file. 
If you want to test locally and build the docs, follow the instructions [here](https://github.com/cal-adapt/climakitae/blob/main/docs/README.md). **You'll also need to install cmip6_preprocessing into your local climakitae-tests conda environment:** ``pip install cmip6_preprocessing``
> Add uncertainty utils functions/classes to climakitae API in readthedocs

- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/meteo_yr.py
- climakitae/threshold_panel.py
- climakitae/warming_levels.py
This PR combines app.retrieve() and app.retrieve_from_csv(). It allows the user to retrieve the data from a configuration csv file using app.retrieve() by setting the argument `config` to the filepath of a file, i.e. "config.csv". For example: 
This will work to retrieve the data as normal: whatever settings are contained in app.location and app.selections (as set in app.select() ) 
```
app.select() # Make your selections 
data = app.retrieve() 
```
This will also work, duplicating the behavior of app.retrieve_from_csv()
```
app.retrieve(config="config.csv")
```
This will also work, **but eventually I will delete this function**. I need to replace it in the existing notebooks though, first. 
```
app.retrieve_from_csv(config="config.csv") 
```
**To test**: Just try running the example code …
> Add config argument to retrieve

- climakitae/threshold_tools.py
This PR creates a new function `_get_return_variable` that consolidates code that was repeated between the `get_return_value`, `get_return_prob`, and `get_return_period` functions (I think this will make things clearer/easier to keep track of as we change things that affect all three user-facing functions!)
> Simplify repeated code in threshold_tools

- .github/workflows/ci.yaml
- environment.yml
This PR removes xclim from environment.yml and instead pip installs it and its dependencies in the GitHub workflow that runs the test environment.
> Move xclim install to GitHub testing workflow

- .github/workflows/ci.yaml
- environment.yml
This PR fixes the missing `numba` package in the testing environment by breaking the cache by incrementing `CACHE_NUMBER` and by adding `numba` to `environment.yml` as it is needed by `xclim` tests.
> Fix NoModule numba Error in test environment

- climakitae/selectors.py
- climakitae/uncertain_utils.py
- setup.cfg
Necessary climakitae changes to revert to pangeo image tag 2021.10.19. I left environment.yml and requirements.txt as is. 
You'll also need to pip install xclim: ```pip install xclim==0.36.0```
**To test:**
Try running all the panels- app.select, app.expore.amy, app.explore.thresholds, app.explore.warming_levels and perhaps some of the timeseries stuff if you're so inclined. I believe @vicford is working on reverting some of the notebooks to work for this image.
> Downgrade image

- climakitae/derive_variables.py
- climakitae/utils.py
As requested, multiple changes have occurred for heating/cooling degree days:
1. The order in which CDD/HDD is computed is now flipped, so that CDD and HDD are calculated prior to spatial averaging.
2. CDD/HDD function now has the functionality to accept a different threshold for heating/cooling. 
**Please test that the `compute_hdd_cdd` function works as desired in the INTRO dfu notebook, Section 4**
4. A new heating/cooling degree hours calculation is provided
**Please test that the `compute_hdh_cdh` function works as desired in the INTRO dfu notebook, Section 5**
INTRO DFU notebook is also under review to reflect these changes as well: https://github.com/cal-adapt/cae-notebooks/pull/42
> Updates CDD+HDD function and adds degree hours calculation

- climakitae/data/variable_descriptions.csv
The variable description for the minimum and maximum air temperature used to be "Daily min/max..." whether it was daily or monthly. This PR fixes that! Now it just reades "Min air temp...."
This will change the name of the dataset that is returned as well.
> Update variable descriptions for min/max daily and hourly air temperature 

- climakitae/selectors.py
Quick fix as getting a warning about geopandas.sjoin "op" parameter has been replaced by "predicate", and will start barking at us eventually/soon (https://geopandas.org/en/stable/docs/reference/api/geopandas.sjoin.html)
**To test**: grab station data and make sure it returns data. This barked at me for the "Burbank-Glendale-Pasadena Airport" selection in the temperature_distributions notebook (cae-notebooks/dfu_pdfs branch), but not in app.select, but should be done if that's going to break selectors in the future
> Geopandas spatial join warning update

- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/selectors.py
This PR modifies how the data is retrieved to account for the addition of the member_id (i.e. ensemble) dimension to the zarrs in the catalog. You'll notice the simulation coordinate now shows the downscaling method, simulation name, and ensemble. 
**Note:** I'll replace the catalog link in the code with a link to the permanent location after I communicate with Brian.
> Retrieve LOCA2 data using new catalog link

- climakitae/timeseriestools.py
- tests/timeseriestools/test_timeseriestools_monthly.py
This PR addressed two outstanding loose ends in timeseriestools.py
https://trello.com/c/g35VOHPb
and
https://trello.com/c/LRwiznwG
- You can no longer select a resampling window smaller than the time resolution the data is starting with
- You can select min, max, and/or percentile all at once instead of only one at a time.
> Timeseries update

- climakitae/data_loaders.py
This PR fixes a bug that was raised when the user tries to retrieve historical + SSP data for a time slice that is out of the bounds of the historical time range. For example, ```app.retrieve()``` would raise an error if you had selected "Historical Climate" and one of the SSPs, but only had selected a time range of 2090-2100 (which doesn't include any data in the historical climate range of 1980-2015). 
**To test**: Make sure you can retrieve the data when you have selected both "Historical Climate" and an SSP for a time slice that is completely in the future (i.e 2030-2035).
> Fix historical + SSP data retrieval bug

- climakitae/data_loaders.py
I made a mistake when trying to fix a bug in [a PR I pushed yesterday](https://github.com/cal-adapt/climakitae/pull/204), and didn't actually solve the bug. Oops. This PR actually fixes the bug. I think we all missed it because it's kind of a tricky bug to find.
**To test:** Make sure you can retrieve the data when you have selected both "Historical Climate" and an SSP for a time slice that is completely in the future (i.e 2030-2035).
> Fix mistake from previous PR

- climakitae/data_loaders.py
This PR fixes a bug in the file retrieval that uses wildcard matching to deduce the filename for a given simulation and scenario. Previously, it incorrectly would pull "EC-Earth3-Veg" data instead of "EC-Earth3" data, because the substring "EC-Earth3" is in both simulation names. In the code, I added a "." to indicate the the wildcard shouldn't continue after the simulation (maybe that makes no sense...)
**To test**: Not sure how to test this, since no error was ever raised. Just look over the code.
> Fix wildcard matching for zarr retrieval

- climakitae/data_loaders.py
When working on a different feature, I noticed a bug in the data retrieval of the derived variables. The data retrieval was not working for derived variables if you tried to call `app.retrieve` more than once, because the backend code was setting `selections.variable_id` to a string instead of a list. This fixes that! 
**To test**: Try retrieving a derived variable, which could be one of the following: 
1) Hourly relative humidity
2) Hourly, daily, or monthly dew point temperature 
3) Hourly specific humidity 
4) Hourly wind speed
> Fix data retrieval bug for derived hourly variables

- climakitae/data_loaders.py
- climakitae/view.py
This PR retrieves the entire spatial domain of the model data when station data is retrieved, then finds the closest gridcell using the entire dataset. Previously, the model data could have been subsetted depending on if the user had selected a certain area subset in ```app.select``` before picking the station. Hopefully this solves the issue of the station data sometimes returning nans. My suspicion is that that was occurring because sometimes the closest gridcell was one that had been "NaN"ed by the area subsetting. 
This PR also fixes the erroneous "please read your data" warning in ```app.view``` for station data, since the rechunking in the bias correction sets the dask chunks to an empty dask "Frozen" object instead of "None".
**To test:** Retrieve some station data using the area …
> Fix bugs in station data 

- climakitae/core.py
This PR removes ```app.retrieve_from_csv()``` as an option. From my memory, this was legacy code that no notebooks use anymore. **The same functionality can be achieved** by using ```app.retrieve(config="file.csv")```.
Purpose of doing this is just to clean up ```core.py```. 
**To test**: Can someone help me verify that no notebooks use the outdated call ```app.retrieve_from_csv()```? I already checked and couldn't find anything but it's definitely possible I missed something (perhaps in cae-examples?)
> Remove app.retrieve_from_csv()

- climakitae/core.py
- climakitae/data_loaders.py
- climakitae/explore.py
- climakitae/meteo_yr.py
- climakitae/selectors.py
- climakitae/threshold_panel.py
- climakitae/uncertain_utils.py
- climakitae/warming_levels.py
This is a purely backend change, the user won't notice anything different. Now, map_view is an attribute of DataSelectors instead of Application. This cleans up the code quite a lot. 
**To test:** Just play around with climakitae (i.e. `app.select()`, `app.view()`, `app.explore`...) and make sure you don't find any weird bugs with the display of the map in the panel.
> Rewrite map_view to be an attribute of DataSelectors

- climakitae/selectors.py
This PR is branched off an outstanding branch `mapview`. It provides the formatting changes required to work around poor formatting in the intermediary pangeo image from 2022.09.21. This image appears to function fine but the figure displays are buggy. The resolution is quite bad and the sizing doesn't make much sense (which is why I had to resize the images and change the fontsize). 
Run this climakitae branch in the Pangeo image tagged for 2022.09.21 (You will need to change the date in your local Makefile). DO NOT RUN IN THE HUB-- the hub image is set to 2021.10.09, and cannot be changed by anyone but Brian. 
For those who may ask, modifying the dpi of the images does NOT have any effect on the figure resolutions. The version of panel in the 2022.09.21 is buggy. I have tried modifying …
> Formatting fixes to sync with Pangeo image: 2022.09.21

- climakitae/selectors.py
Tianchi had noticed a bug in the map display of lat/lon selection. If you selected too large of a lat/lon region using the slider box thing, ```app.select()``` would throw an error. This PR just resolves that! 
See this comment for the error message (which you should *not* see in this branch!): https://github.com/cal-adapt/climakitae/pull/210#pullrequestreview-1415613228
**To test**: Open up ```app.select()``` in this branch. Try to use the sliders to adjust the lat/lon selection to a large region. Ensure no error is raised.
> Fix bug in display of lat/lon selections

- climakitae/data_loaders.py
- climakitae/selectors.py
We don’t have gridded data at 3km for SSPs 585 and 245 but ```app.select()``` shows them as options for 3km station data, then promptly raises a nonsensical error when you attempt to retrieve the data. 
This PR does the following: 
1) Removes SSP 585 and 245 as options when 3km is selected
2) Modifies the ```data_loaders``` module to raise a descriptive error if no data is found. Hopefully this should never actually be raised, but is in place for us developers in case things fall through the cracks. 
**To test**: Ensure that when you select "station" and "3km", only Historical Climate and SSP 375 are shown as options in ```app.select()```
> Fix bug in 3km data retrieval for SSPs 585 and 245 

- climakitae/data/variable_descriptions.csv
- climakitae/selectors.py
- climakitae/unit_conversions.py
ON HOLD FOR NOW: do not review.
This PR adds in the LOCA2 precipitation data with its correct units and unit conversion options. It also modifies how related unit conversions for other precip variables (which have units of mm) are coded in. 
**To test**: Try pulling the precip variables, for LOCA, WRF, and a combination of the two, with different units. Make sure the units and data all look as expected. **TIP**: When testing with the LOCA data, just retrieve and load a year or two of data for a small spatial region to avoid blowing out the memory.
> Add in LOCA2 precip with correct units and unit conversions

- climakitae/data/variable_descriptions.csv
- climakitae/data_loaders.py
- climakitae/derive_variables.py
The derived variable retrieval only worked if you selected the default variable. For example, you could grab dew point in Kelvin, but not degF or degC. This PR fixes that issue.
> Fix unit conversions for derived variables

- climakitae/data/variable_descriptions.csv
- climakitae/data_loaders.py
- climakitae/derive_variables.py
- tests/derive_variables/test_derived_variables.py
This PR adds wind direction as an hourly variable. 
**To test**
Try retrieving hourly wind direction! Noting, would recommend this for a coarse resolution and/or small location because of the data involved in computing. 
***Note:*** Wind direction is not normally displayed as such. I have a trello card up to add a AE-branded cyclic colormap that I'll get to next, as well as setting the colorbar limits to 0-360. **If** we decide to pursue wind velocity in the future (magnitude + direction), we can investigate barbs for wind direction as an option too.
> Add wind direction as derived variable

- climakitae/data/variable_descriptions.csv
- climakitae/selectors.py
This PR adds in the functionality for selecting and retrieving monthly LOCA2 variables using climakitae app.select() and app.retrieve()
NOTE: You'll see I had to swap the order of the timescale dropdown into an unintuitive order: daily, monthly, hourly. This is due to panel being a bit annoying and filling in the wrong option as they are subsequently restricted and expanded depending on the selection (please PM me if you want a more detailed explanation!). I know it sucks, but I think this is the best fix. 
**To test**: Try retrieving monthly LOCA2 data!
> Add in selection of LOCA2 monthly variables 

- climakitae/data_loaders.py
- climakitae/meteo_yr.py
- climakitae/selectors.py
- climakitae/view.py
- climakitae/warming_levels.py
This PR addresses the issue of plotting gridded data that's only one grid cell. Previously a bug had been raised by ```app.explore.warming_levels()```. Also, in ```app.view()```, data that was only one grid cell would output a weird lineplot with simulation or scenario on the axis. Now, data with only one grid cell is shown as a scatter plot. 
**To test**: Confirm that app.view() still works-- check a view geometries, station data, area average, etc. To make sure I didn't *introduce* any bugs with this bug fix. Confirm that ```app.explore.warming_levels()``` works for small geometries (i.e. a small county at 45km resolution)
> Plotting small geometries: A fix

- requirements.txt
This PR just bumps `scipy` explicitly to `1.9.1` so that pip install sets right version.
> Set scipy==1.9.1 in requirements.txt

- .github/workflows/ci.yaml
This PR fixes the GitHub miniconda env cache environment. Hopefully tests will run better and faster now.
> Fix slightly non-optimal GitHub workflow

- environment.yml
- requirements.txt
This addes `pygeos=0.13` to `environmental.yml` and `requirements.txt` to address the requirement of `dask-geopandas` encountered in test added to #238.
> Add pygeos to environmental.yml and requirementss.txt

- setup.cfg
Revert adding `pygeos` to `setup.cfg` as it is not strictly required for `climakitae`
> Revert adding pygeos to setup.cfg

- climakitae/data_loaders.py
The HadISD zarr stores used to be in the AWS tmp directory. Now they are in the main catalog, so I fixed the filepath. 
I updated the QuantileDeltaMapping code in `data_loaders` following Beth's guidance to set a window of 90 days (+/- 45 days) to account for seasonality.
> Update HadISD in backend retrieval code

- climakitae/data_loaders.py
This should fix the issue in the AMY panel that popped up after the data_loaders refactor: seems to require that there be a singleton dimension for scenario if 'Historical Climate' is present without any SSP. This PR adds one.
> Add singleton 'scenario' dimension for 'historical climate'

- climakitae/data_loaders.py
The bias-correction already uses the same range in the gridded data as the station data that was read-in. This changes that reference range in one other spot for consistency, where we make sure the gridded data selected is expanded to include the same range as the station obs.
> Station range for consistency.

- climakitae/data_loaders.py
This PR fixes degradation introduced in https://github.com/cal-adapt/climakitae/pull/238, after which 'retrieve' failed to return anything for "Historical Reconstruction" (e.g. the reanalysis-driven WRF simulation). 
The structure of the xr.DataArray in which the ERA5_WRF data is returned is different from before when "Historical Climate" and "Historical Reconstruction" are both selected. The "ERA5_WRF" label is appended along the "simulation" dimension, but the scenario dimension is labeled "Historical" to avoid the inefficiency of a sparse array with two values along the 'scenario' dimension.
> Restored retrieval of reanalysis-driven WRF run

- climakitae/data_export.py
Adds two new fancy formats for how TMY data is used: .epw (energy plus weather) and .tmy (typical meteorological year)
These formats are effectively csv files with specific headers and information included. Sources are included in the header construction functions. 
---
To test:
Run through the AMY_to_TMY notebook in the amy_to_tmy branch on cae-examples (https://github.com/cal-adapt/cae-examples/pull/47) and play around with the file_ext as both "tmy" and "epw" in the export code cell (the very last one)
> Export file options for TMY data

- docs/README.md
- docs/climakitae.rst
- environment.yml
The readthedocs page doesn't automatically update (it should!! see [this](https://trello.com/c/jTwpvNkP/347-troubleshoot-readthedocs-issue) open trello card). So, here I force-refreshed the documentation to update it with the current code. I branched off of my effective temp branch (eft) so that the index code was included in this. 
I also noticed an issue when trying to rebuild the conda environment, which is used to build the documentation. Just some minor formatting issues, which I easily resolved :D
> Refresh the current documentation. Fix broken environment.yml file

- climakitae/core/data_export.py
This PR allows users to export xarray Dataset to the CSV format. Previously only DataArray can be exported to CSV. Now, users are able to export station data as well as all the Dataset outputs from the threshold_tools_basics and threshold_tools_application_examples notebooks.
**Implementation details:**
- The function `export_dataset` no longer raises an exception when users export a Dataset. The Dataset would be exported via `_export_to_csv`.
- The functions `_export_to_csv`and `_metadata_to_file` are branched depending on whether the data to export is a DataArray or a Dataset. 
- Helper functions are created/updated to hold code that works for both data types.
- Existing code specific to DataArray is moved to `_dataarray_to_dataframe` with structural changes needed to leverage the …
> Export Dataset to CSV

- docs/conf.py
- setup.cfg
Just had a thought that we should tag the current software as `0.0.2` so that it can be loaded as a pre-refactor software release.
> Tag software as 0.0.2

- climakitae/core/data_export.py
- docs/data.rst
This PR updates data export-related readthedocs documentation: "working with data" page and `export` function docstring. The updates are similar to those applied to the notebooks in [this PR](https://github.com/cal-adapt/cae-notebooks/pull/65).
> Update export readthedocs documentation

- climakitae/core/data_export.py
As promised in https://github.com/cal-adapt/climakitae/pull/270, this PR adds to the headers of exported CSV tables, the names of climate variables associated with the weather stations. 
**E.g.** "Air Temperature at 2m" in the 2nd row of the table below.
> Add climate variable names to CSV exported from station data

- climakitae/core/boundaries.py
- climakitae/core/data_interface.py
- climakitae/core/data_view.py
- climakitae/explore/uncertainty.py
This PR moves `Boundaries` data loading to a `load` method that is then called on `DataInterface` init.
> Move Boundary data load out of init and to load method

- climakitae/explore/warming.py
1. Colormaps for variables should be ae_diverging instead of their assigned colormap according to the data_descriptions file, with the exception of air temperature and dew point temperature. This fixes an issue Naomi had noticed specifically for precipitation, but upon testing was relevant for all other vars.
2. The assignment to humidity to 100% when displayed had a typo, now fixed.
----
To test:
Run the warming_levels notebook and make sure that:
- air temp and dew point have ae_orange colormaps
- relative humidity is on a 100% scale (range is not -5 - 5)
- any other variable selection has a diverging colormap
> updated cmap update for redesigned warming

- climakitae/core/data_load.py
This PR replaces `xclim.core.calendar.convert_calendar` which outputs `CFTime` with `xarray.Dataset.convert_calendar` which outputs `datetime64`.
> Change function to convert calendar to noleapyear for station data

- climakitae/core/data_export.py
This PR adds .epw and .tmy file export functionality, including a function to determine the timezone offset from UTC and the elevation, which are mandatory fields in these files. 
Note: I am unsure why the lint is failing
---
To test:
Run the updated TMY methodology notebook in PR (https://github.com/cal-adapt/cae-notebooks/pull/82) in this branch
> TMY export file format

- climakitae/tools/indices.py
This PR changes the way the Fosberg Fire Index is generated. Removes 2 where statements that tried to reclass values < 0 and > 100 to 0 and 100. Unfortunately, the `xr.where` statements reclassified data outside of the spatially clipped region. PR uses `np.clip` to clip values outside of [0-100] to the boundary values.
> Fosberg Derived Index fix where statements reclassing data incorrectly

- climakitae/core/data_view.py
This PR removes the `sopt` parameter that is passed to `hvplot.image` and not recognized. The `sopt` parameter seems to have been used when data is divergent but I am not sure what it's intended purpose was?
> Remove sopt from hvplot.image call

- climakitae/core/data_export.py
- climakitae/data/hadisd_stations.csv
Previously, TMY file export was breaking on using an API requests call to the EPQS DEM to obtain elevation. As far as I can tell, this is on the EPQS side of things and not on our code base. To address this, I added the corresponding elevation values from `wecc-station` csv to the `hadisd_stations` csv file that is used in the climakitae backend, and modified the TMY code to obtain the corresponding elevation value when requested. At present, when a custom location is passed, elevation is set to 0. This will be a future fix. 
N/A
**Please describe the tests that you ran to verify your changes. Provide instructions so we can …
> Bug fix on TMY: elevation in export

- climakitae/core/data_export.py
- climakitae/core/paths.py
Making changes to data_export to remove redundant code, clean up, and give more buffer to user partition
 
- Added compression for local exports. This doubles as a safety buffer as we estimate on non-compressed size.
- Fixed hardcoded paths.
- Added option to explicitly specify which export method to use.
JupyterHub user partitions have filled up and frozen users out and the large files that did it were netCDF exports. This PR should resolve this in most cases.
- [ x ] New feature (non-breaking change which adds functionality)
**Please describe the tests that you ran …
> Make updates to data_export

- climakitae/data/hadisd_stations.csv
When the longer timeseries HadISD data was put into our s3 bucket, some stations were renamed due to overlap and other issues, but we didn't update the existing hadisd_stations csv with the newer names. This PR updates this. 
Please test in https://github.com/cal-adapt/cae-notebooks/pull/101
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] New and …
> UpdateS station ids for renamed data in bucket

- climakitae/util/dev_logging.py
- climakitae/util/logging.py
Creating a comprehensive logger for developers to view what is going on in the AE library. This PR allows developers to wrap functions within modules with a `log` function, which prints the runtime of the function and all the sub-functions of the function that exist within the same module. It additionally will log any other sub-modules reference within the current module (i.e. if you try to log DataInterface, it will also log functions within the DataParameters class).
Addition of a library-facing logger in `climakitae.util.logging` to increase visibility of function execution and runtimes in the codebase.
This has been developed because it increases the visibility of what functions run at execution (good for …
> Creating Library Logger

- climakitae/core/data_interface.py
- climakitae/core/data_load.py
This PR adds data warnings for when users pick large amounts of data that will take long periods to run operations.
Adding data warnings for data retrieved over 1GB in size. Data over 5GB given more emphatic message. Data over 10GB given a sever warning.
User can download very large datasets without knowing the consequences of doing so as far as run time on even the simplest of operations. As warning before retrieval is not ideal due to different paths to access the data it seemed warranted to put a warning after data retrieval but before trying to load into memory. 
None
**Please describe the tests that you ran to verify your changes. Provide instructions so we can …
> Large Data Warnings

- climakitae/core/data_load.py
This PR patches `ck.load` to remove the ProgressBar that was adding in #337 as the loading process has a memory spike without ProgressBar and then goes back to "normal" size but with ProgressBar the memory stays high.
See Issue #345 
- [N/A] Any dependent changes have been merged and published in downstream modules
> Fix ck.load memory usage introduced by using ProgressBar

- requirements.txt
READTHEDOCS build is crashing. Looks like from logs that it is grabbing `2024.5.0` version. Need to pin `dask` at 2022.9.1.
> Pin dask at 2022.9.1 for READTHEDOCS

- climakitae/core/data_export.py
This PR adds a CSV file size estimate and helps protect file system from filling up. The file estimate is just a 1st approximation using 150 characters per line as a guess. It also removes the 0.85GB CSV file limit (let users decide if the file is too big for their use). We still warn of larger than Excel can handle and warning that large CSV export will take awhile.
https://trello.com/c/5J8YQ2HI/569-ability-to-estimate-manage-file-sizes-csv
Protect HUB file system from filling up from CSV export.
- [ x ] New feature (non-breaking change which adds functionality)
**Please describe the tests that you ran to verify your changes. …
> CSV file export size estimate and disk space protection

- climakitae/core/data_load.py
Howdy, I accidentally introduced a small bug in my [last PR](https://github.com/cal-adapt/climakitae/pull/358). Basically, that PR accidentally made it so for variables with only a single unit option, an error was raised when you tried to retrieve the data. YIKES! Obviously not good behavior. I fixed that in this PR. To review, perhaps just review the code, or maybe try to retrieve a variable with only one unit option to make sure it all looks good. 
- [n/a] Test A
- [n/a] Test B
- [n/a] I have made corresponding changes to the documentation
- [n/a] I have added tests that prove my fix is effective or that my feature works
> Fix small bug I introduced on accident regarding units

- climakitae/core/data_load.py
This PR shifts the time dimension by 12HR for two "troublesome" LOCA2 simulations, such that they match the time formatting of the other LOCA2 simulations. Since the data is daily, this shouldn't effect anything. 
It solves the issue of every other day in the daily retrieved LOCA2 data being set to NaN (!!!!), which is obviously not desired behavior. 
n/a
- [n/a] I have added tests that prove my fix is effective or that my feature works
> Shift time dimension for troublesome loca2 sims

- climakitae/explore/warming.py
This PR separates visualizing code from wl.calculate, allowing visualizations and calculations to be done separately.
We want to separate calculations and visualizations as we progress towards a GUI specific and calculations specific divergence between packages.
> Separating WL calculate and viz

- climakitae/explore/warming.py
This PR includes changes for calculation and visualization separation (https://github.com/cal-adapt/climakitae/pull/379) and also makes a cleaner visualization for LOCA2 simulations in `wl_approach.ipynb`. Below are the before and after images representing LOCA2 simulations using the `WarmingLevelVisualize` class.
**This can be tested with https://github.com/cal-adapt/cae-notebooks/pull/103**
Before this PR:
After this PR:
We want to create more interpretable graphics for notebook users.
> Changing plot type for LOCA visualizations shown in `warming_levels_approach.ipynb`

- climakitae/explore/vulnerability.py
Causes an error when selecting for BC WRF models because the simulation names are longer than just the simulation itself with warming levels (also includes information about if the data came from an SSP/Historical Period).
> Reverting simulation selection code to what it was before

- climakitae/util/utils.py
This PR changes the behavior of `get_closest_gridcell` by using a tolerance for how far it will search for a gridcell. The tolerance is derived from the dataset resolution attribute. If the input point is farther than one grid cell away from any of the input data it will return `None`.
#388
See issue for motivation.
- [ x ] Tested on HUB
> Closest cell fix for `get_closest_gridcell` util function

- climakitae/core/data_interface.py
- climakitae/explore/amy.py
- climakitae/explore/thresholds.py
- climakitae/explore/timeseries.py
- climakitae/explore/warming.py
- Remove `param`’s parameter descriptions from docstring because ANSI escape sequences in them make them look wrong and difficult to read on Read the Docs. 
- Remove `param`'s docstring signatures because they are also hard to read.
See [this Trello card](https://trello.com/c/umgIWU6f) for an example. 
Improve presentation of the documentation.
Checked the preview: https://climakitae--394.org.readthedocs.build/en/394/
- [not relevant] I have made corresponding changes to the documentation
- [not relevant] New and existing unit tests pass locally with my changes
- [not relevant] Any dependent changes have …
> Remove ill-formatted documentation

- climakitae/core/data_interface.py
This PR updates the `_update_scenario` param trigger to properly set the historical scenarios after changing the affected widgets.
previously we tested if one list was in another (currently hist. scen. options vs. possible new options) using `in`. This apparently does not work as it was returning false when it was true. I therefore wrote a function that converts the lists into numpy arrays and compares them.
selections are being changed after parameters are being set and bring back incorrect data. Most obviously a problem when not using the GUI as you can't see that historical selections have changed.
- [ x ] Bug fix …
> Update Scenario Param trigger fix

- climakitae/explore/warming.py
- climakitae/util/utils.py
During a WL approach, the simulations are all stacked together, across models and SSPs. However, this causes simulations to appear that do not necessarily exist. The helper function in this PR is to address this issue, by dropping erroneous simulations from each spatial scale of WRF simulations WITHOUT having to load them all in and dropping NaN simulations.
Addresses #397 .
We want to drop erroneous simulations without having to load them all in.
> Adding helper function to remove incorrect WRF sims during WL approach

- climakitae/core/data_interface.py
- climakitae/explore/warming.py
Add functionality to optionally load in warming levels. This allows for lazy loading with xarray and for more data manipulation/subsetting before having to load data into memory.
We want to have the option to load in warming levels data or not. This can be toggled with the `wl.wl_params.load_data =True/False` parameter.
In a notebook using warming levels.
> Optionally Load in Warming Level data

- climakitae/explore/vulnerability.py
Small condition change, since we are hard coding using 3 km and hourly data selections for WRF data in pilot.
> Add logic to limit SSP selection to only 3-7 for WRF for pilot

- climakitae/explore/vulnerability.py
Re-adding removed param from merge conflict. Was breaking `cava_data` but now it should be fixed.
> Re-adding removed param from merge conflict

- climakitae/explore/warming.py
I improved the visualizations for the first panel in ```wl.visualize()```. I improved the colormap, addressing this old [issue](https://github.com/cal-adapt/climakitae/issues/299) Naomi raised. I also added a colorbar and reasonable plot titles. For data with more than 4 simulations, a single plot is shown with a dropdown widget for toggling between simulations. For data with 4 or fewer simulations, postage stamp maps are created. 
I also added the ability for a scatter plot to be generated for data that is only a single grid cell. It's not that informative, but at least it shows you something, and doesn't throw an error :) 
**To test**: Run the warming_levels.ipynb notebook up until ```wl.visualize()``` (section 1c in the notebook). Try a few different data options. 
**NOTE**: I wasn't …
> Improve visualizations in the first panel of wl.visualize

- climakitae/explore/warming.py
Addressing small bug with warming levels when slicing warming level data that goes beyond 2100. Currently, it creates smaller slices and centered the years incorrectly. Instead of -180 to 168 for a 30-year monthly WL that is centered around 2086 (so missing the last year), it creates a time index that is from -174 to 174 instead (wrong). 
This PR addresses this issue and centers the warming level slices correctly.
You can see this behavior by changing the default lat/lon params in `warming_levels.ipynb` to:
```
wl.wl_params.latitude=(34.0,34.03)
wl.wl_params.longitude=(-117.5,-117.45)
```
and checking out warming level slice 4.0. You can also see this behavior in a larger lat/lon subset, this just filters down the data to two gridcells so you can …
> Debugging Beyond End of Century WL Behavior

- climakitae/core/data_interface.py
**See header below "How to test" for instructions on how to test this PR**
When I wrote the new ```get_data``` function for the climatekitae_direct_data_download notebook (the functions that let you access/download data without the GUI), I wrote it such that you could only retrieve data for a single scenario (because it was way more simple programmatically). 
In working on the warming levels code, I realized we really need to be able to pull multiple scenarios, like the selections GUI does. So, in this update, I allow you to use a list as an input for the scenario object. 
In the climakitae_direct_data_download notebook, try retrieving and viewing different data options using the following two functions: ```get_data_options``` and ```get_data```.
**Please describe the tests that you ran …
> handle list input for scenario

- climakitae/core/data_load.py
Looks like unit conversion was happening two times in the data retrieval code. An error was being raised for monthly precip data retrieval in the first conversion because the frequency attribute had not yet been added by that time in the workflow, raising an error for unit conversion. 
I'm not sure if this may raise other issues down the line. I tested a few conversions and it seems fine but maybe there are things I'm not thinking of. Time will tell...
> Unit conversion happening twice

- climakitae/tools/indices.py
- climakitae/util/utils.py
Making WRF WL derived vars work again.
This broke because of a change I made for filtering WRF WL simulations. Derived indices weren't accounted for, and now they are, in a very hot fix way. All derived indices currently use temperature, so that is the psuedo-variable we're using to replace the derived index variable when looking through the catalog for valid WRF WL simulations.
<br>
> Making bug fix for WRF WL derived vars

- climakitae/core/data_interface.py
Enable user to retrieve data using ```get_data``` function for a lat/lon spatial subsetting. 
For example:
```
get_data(
variable = "Precipitation (total)", 
downscaling_method = "Dynamical", 
resolution = "9 km", 
timescale = "monthly", 
scenario = "SSP 3-7.0 -- Business as Usual",
latitude=(32.5),
longitude=(-125.5, -114) 
)
```
Two new arguments were added: "latitude" and "longitude". Enables the user to input a tuple of lat/lon bounds to retrieve, analogous to what is done in the backend by the GUI
We often retrieve data using a lat/lon bounding box. Added this feature so we could do that without using the GUI. 
Try retrieving data using the "latitude" and "longitude" bounds. 
<br>
> Enable retrieval using lat/lon bounds for get_data function

- climakitae/explore/warming.py
This PR is a quick fix for bad function ref and unused function imports in Warming.py
> Fix bad refs in Warming.py

- climakitae/core/data_interface.py
- climakitae/data/variable_descriptions.csv
- climakitae/util/utils.py
- tests/data_interface/test_variable_descriptions_csv.py
Enable users to view and retrieve derived variables/indices without using the DataInterface GUI. This wasn't previously an option. 
- Derived variables/indices are now available for viewing using the existing function ```get_data_options()```
- Derived variables/indices are now available for retrieval using the existing function ```get_data()```
- Added a new column "dependencies" to the variable_descriptions.csv file, which is used to determine variable dependencies for the derived variables/indices. This helped me determine the correct subset/combo of options for each variable to return to the user. 
- Wrote some unit tests (hell yeah!!) 
When I wrote the two functions ```get_data_options()``` and ```get_data()```, I didn't realize they didn't allow you to view/retrieve derived …
> Enable non-GUI view and retrieval of derived variables/indices

- climakitae/core/data_load.py
The warming level attribute description had a small typo "Celcius". Fixed to "Celsius". 
Fixed a typo, and relevant other comments with typo. 
Typo. 
How to test:
Retrieve data at a desired warming level and check the warming level attribute description. For example:
```ds.warming_level```
- [N/A] 80% unit test coverage
- [N/A] Documentation
- [N/A] All functions/adjusted functions documented in the [readthedocs](https://climakitae.readthedocs.io/en/latest/).
- [N/A] Documentation is pushed
- [N/A] Complex code commented
- [N/A] Helper functions hidden with `_` before the name
- [N/A] Context of function is clearly provided
- [N/A] Intent of function is provided
> Fixes small typo in WL attribute

- climakitae/core/data_interface.py
- tests/data_interface/test_get_data.py
Retrieve derived indices using a warming levels approach. And, some unit tests. 
I previously thought I had implemented this feature in PR #462 , but I forgot to enable the ability to retrieve the data using both a time-based and a warming level approach. 
Try to retrieve the Derived Indices (under the "Derived Indices" button in the GUI) using a Warming Level approach. Try with both the DataInterface GUI(i.e. `selections.show()`)  and with `get_data()`. 
The following are the derived variable options: 
- Fosberg fire weather index
- Effective Temperature
- NOAA Heat Index
> Retrieve derived indices using a warming levels approach

- climakitae/explore/vulnerability.py
The `vulnerability.py` was missing the SSPS import from `core.constants.py`
Added the import, and added all relevant missing "spaces" to where SSPs are set as defaults. Will update the notebook for language as well. 
`cava_data` function was breaking. 
- [TO BE FIXED IN PR] Any notebooks known to utilize the affected functions are still working
> Bug fix: vulnerability.py adding SSP import

- climakitae/explore/threshold_tools.py
- climakitae/explore/vulnerability.py
IOU informed us that for specific arid/desert locations when running 1-in-100 precipitation event with LOCA produces a “non-finite value” error, which breaks the code and stops the run. The issue is caused by nan values being produced in the threshold_tools.get_block_maxima function, specifically in the groupby option for selecting max/min when calculating the ams series prior to calculating return values that is passed to vulnerability.cava_data._metric_agg(). 
This PR: 
- Implemented a patch fix just for precipitation by setting the NaN fill value to 0 in the max scenario (for max precip, 0 will always be the minimum – this is a semi-safe solution, but not 100% accurate), and by setting the NaN fill value to the precipitation max value in the min scenario (for min precip, we cannot set …
> Bug fix: threshold tools nonfinite value bug when calculating 1-in-X precipitation events in arid regions

- climakitae/core/constants.py
- climakitae/explore/vulnerability.py
- climakitae/explore/warming.py
Adds historical GWLs as viable options into `cava_data` functionality in the `vulnerability_assessment.ipynb` notebook.  I also went ahead and changed the language of the `anom` parameter in `warming.py` to be clearer, but **did not modify the underlying code** as to **how** `anom` is calculated.
**IMPORTANT**: I added two new constants to constants.py of which models should not be returned if the warming level is selected as 0.8°C. This should be implemented more broadly across the code base for 0.8°C in general. 
**How to test**:
- Try to retrieve 0.8 and 1.2 as warming_level options in cava_data function **and** 
- Ensure that **for a 0.8°C GWL** for WRF EC-Earth3-Veg is not returned, and for LOCA EC-Earth3_r4i1ip1f1 all ssps, EC-Earth3-Veg_ri1p1f1 all ssps, and EC-Earth3-Veg_r5i1p1f1 …
> Adding 0.8 1.2 GWLs into cava_data options

- climakitae/util/utils.py
Specifically in the annual_consumption_model / degree_days notebook, the second convert_to_local_time with gridded data is failing
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [13], line 2
1 # do simple timezone conversion instead
----> 2 data_dfz = convert_to_local_time(data_dfz, selections)
File ~/src/climakitae/climakitae/util/utils.py:640, in convert_to_local_time(data, selections)
636 elif selections.data_type == "Gridded" and selections.area_subset != "none":
637     # Find the avg. lat/lon coordinates from entire geometry within an area subset
638     from climakitae.core.boundaries import Boundaries
--> 640     boundaries = Boundaries()
642     # Making mapping …
```
> "convert_to_local_time" failing on gridded data wrt Boundaries

- climakitae/core/data_load.py
WRF domain was trimmed by 10 grid cells for every resolution. 
WRF output needs to be trimmed, because data at the domain edges has weird numerical stuff going on and it takes some time to “relax” onto the domain’s grid.
Per an email conversation with Stefan: we recommend trimming ~10 grid points from the right, left, top, and bottom edges of each domain (d03, d02, and d01). Ideally there will be some investigation for the amount of trimming; this is our best guess right now. 
This is what the code does, for 9 km resolution... you can see the untrimmed WRF data (blue) behind the trimmed WRF grid (coolwarm cmap data on top): 
**WE NEED TO UPDATE THE GUIDANCE BUT I DON'T THINK I'M THE RIGHT PERSON TO DO THAT**
Try retrieving WRF data for the entire domain using climakitae. Make sure it …
> Trim WRF domain edges

- climakitae/core/data_load.py
Programmatically rotate winds from WRF grid --> spherical earth. 
We need to rotate U and V to Earth-relative coordinates in order to properly derive wind direction and generally make comparisons against observations. Reference: https://www-k12.atmos.washington.edu/~ovens/wrfwinds.html
Ideally, this should NOT be done programmatically... we should update the zarrs and remove this code. At some point in the future. 
Affected variables: 
WRF hourly: 
- West-East component of Wind at 10m (i.e. "u10") 
- North-South component of Wind at 10m (i.e. "v10")
- Wind direction at 10m (derived from u10 & v10) 
- Wind speed at 10m (derived from u10 and v10) 
**WE NEED TO UPDATE THE GUIDANCE BUT I DON'T THINK I'M THE RIGHT PERSON TO DO THAT**
Run the notebook and files that Nicole will send you in the …
> Rotate wind vectors 

- tests/data_interface/test_get_data.py
Not all the tests were running because the indent was pushed too far to the right. This effects the Relative Humidity tests that follow the Fosberg Fire Weather Index test. 
The three tests are all running (and passing) now: 
Eric found this bug when trying to debug something else. 
No need to test; the github CI should test it for us :) 
- [] Tagged/notified 2 reviewers for this PR
> Fix indent in get_data test 

- climakitae/explore/threshold_tools.py
- climakitae/explore/vulnerability.py
**Summary:** Changing `get_block_maxima` behavior to drop NaNs for any type of variable passed in. Tested against two locations for precipitation. See below for other ways to test this PR.
**Context:**
_Why did these NaNs appear in the first place?_ These values appear _particularly_ for the precipitation 1-in-X calculations used in the `cava_data` function because of the following line: https://github.com/cal-adapt/climakitae/blob/14cebc253cf4ab70d2f91cc4435e63037714a56d/climakitae/explore/vulnerability.py#L173  
where precipitation values are excluded from the DataArray if they are below 10e-10. This is done because we want to remove these little to no precipitation values from 1-in-X calculations, as we only want to count precipitation events where meaningful precipitation actually …
> Making arid regions `get_block_maxima` functionality generalized across variables

- climakitae/core/data_interface.py
- climakitae/core/data_load.py
- climakitae/explore/threshold_tools.py
- climakitae/explore/vulnerability.py
- climakitae/tools/batch.py
- climakitae/util/utils.py
- docs/conf.py
- tests/data_interface/test_get_data.py
Added the ability to retrieve station data using `get_data()` function. Also added the ability to see weather station options using `get_subsetting_options()`. 
These functions were unfinished without station data. Plus, Victoria needs this functionality for some code she’s writing for an IOU. 
Run the notebook `climakitae_direct_data_download.ipynb` in the branch `get-station-data` in `cae-notebooks`. At the bottom of that notebook, there’s some code related to how to use the new functionality from this branch. Try retrieving some different stations, resolutions, etc. Make sure the error messages make sense when you put a bad input, and that the data that is retrieved matches what you input in the function arguments.
> Get station data using get_data() function

- tests/data_interface/test_get_data.py
One of the tests for retrieving station data doesn’t make sense given the original intention I had for the test. The test should test: Does the function return a Value Error Bad Input if you give it a wonky station string (i.e. "the international space station”)? What it currently tests in main: Does the function raise an error if you put "Station" as the `data_type` instead of "Stations"? (not my intended behavior of the test) 
Just noticed this. My bad. 
The test shall test itself (thanks GitHub CI!)
> Update station test 

- climakitae/core/data_load.py
This PR writes the CRS back for LOCA2 data before data is returned. It is dropped along the way.
After upgrading xarray and dependent packages attrs were being dropped that were retained before.
Return data and query the `rio.crs` attribute.
> Assure that CRS and grid_mapping are set correctly before returning data

- setup.py
Inform build process of the context type of README file for Pypi. When attempting to build got this error:
`The description failed to render in the default format of reStructuredText.`
Pypi now requires that `content-type` be set on the README uploaded:
https://github.com/pypi/warehouse/issues/5890
Fixing this in future releases will allow for publishing on Pypi
[How should reviewers test the changes?]
> Pypi requires README context type to be specified

- tests/warming/test_warming.py
Guided by our test coverage sheet, this PR addresses the missing lines of code that are not fully tested within `warming_levels.py`.
We want to increase our test coverage.
You can run `pytest .` in the `climakitae` folder after checking this branch out on the hub, or you can just view the Github actions in this PR and see that the tests (including this PR's) all run successfully.
> Adding full test coverage to `warming_levels.py` in utils

- climakitae/__init__.py
- climakitae/core/data_export.py
- docs/data.rst
This PR adds Zarr export option on the HUB user partition and to s3 scratch bucket. It also removes NetCDF export to s3 as that is limited to <2GB.
It also adds `ck.remove_zarr` function to help users delete Zarr exports on the HUB (Zarr stores are a tree of directories and not easily deleted from the HUB GUI).
Add Zarr support and fix broken export functions.
Export data to Zarr, NetCDF, CSV and reload on the HUB.
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x ] This change requires a documentation update
> Export: Add Zarr local/s3 support, Remove NetCDF s3 support

- climakitae/explore/amy.py
- climakitae/util/generate_gwl_tables.py
- climakitae/util/generate_gwl_tables_unc.py
- climakitae/util/generate_gwl_timing_table.py
- tests/conftest.py
- tests/create_test_dataarrays_single_cell.py
- tests/create_test_dataset.py
- tests/data_interface/test_variable_descriptions_csv.py
- tests/data_load/test_unit_error.py
- tests/derived_variables/test_derived_variables.py
- tests/indices/test_indices.py
- tests/timeseriestools/test_timeseriestools_monthly.py
- tests/unit_conversions/test_unit_conversions.py
Reformat code to adhere to Black 25.1.0 version used by lint CI workflow.
Black stable version changed to 25.1.0. Very minor changes to code formatting (whitespace removal).
[How should reviewers test the changes?]
> Reformat codebase for Black 25.1.0

- climakitae/explore/warming.py
Noticed this in reviewing Eric's latest PR. Simulation is completely printed instead of just the name. Fixing this in this PR.
Make print statement correct
Run `warming_levels.ipynb` with this PR and confirm that the output for warming level data not being completely available looks like the following instead of printing an entire DataArray object:
> Bug fix to `warming.py`

- climakitae/explore/threshold_tools.py
- climakitae/explore/vulnerability.py
- climakitae/tools/batch.py
- climakitae/util/utils.py
- tests/vulnerability/test_vulnerability.py
This PR focuses on the 1-in-X calculation for the CAVA data function. It addresses SCE's concerns with a time bottleneck by parallelizing the compute of 1-in-X calculations across all points at the same time, and also allows for multiple X parameters to be passed into the 1-in-X parameter.
This reduces the overall runtime of the 1-in-X calculation from N points X M simulations X P 1-in-X values to now just M simulations run time. The next PR for time optimization will focus on reducing the M simulations runtime to just 1 simulation run time.
Run `vulnerability_assessment.ipynb` with multiple X's in `one_in_x` param, like
`one_in_x=np.array([20, 100])`
and check that the multiple X calculations are working properly, and that the `one_in_x` distributions are not being fit on the points one …
> Time-optimization changes to CAVA data function

- climakitae/explore/vulnerability.py
- climakitae/util/utils.py
Revert `add_dummy_time_to_wl` function to original design. Function was changed to look for `time_delta` instead of `{time_freq}_from_center`.  `WarmingLevels` `sliced_data` DataArray uses this later time dimension.
Fixes broken `warming_level_approach` notebook.
Run the `warming_level_approach` notebook with this branch loaded for `climakitae`. Plus load the `fix_wl_plot2` branch for `climakitaegui` to fix the visualization plots.
- [ x ] Complex code commented
- [ x ] Any notebooks known to utilize the affected functions are still working
- [ x ] Black formatting has been utilized
> Revert add_dummy_time_to_wl code to previous method

- climakitae/explore/timeseries.py
- tests/timeseriestools/test_timeseriestools_daily.py
- tests/timeseriestools/test_timeseriestools_hourly.py
- tests/timeseriestools/test_timeseriestools_monthly.py
Tests are added to increase the test coverage of explore/timeseries.py. I updated a deprecated call to the Param() class in Timeseries.output_current(). Types hints are added and docstrings are extended.
These changes increase test coverage to 97% (124 statements, 4 missing).
The tests are reorganized into classes for readability and consistency. Type hints are added for readability.
The timeseries_transformations notebook cannot be completely run in its current state because output_current() uses a deprecated method. This change allows the notebook to run in entirety.
```
pytest tests/timeseriestools --cov=climakitae.explore.timeseries --cov-report term-missing
```
If you run timeseries_transformations.ipynb, make sure to select "yes" for area averaging in the …
> Add unit tests for explore/timeseries coverage

- climakitae/util/dev_logging.py
- tests/util/test_dev_logging.py
Added test coverage for `climakitae.util.dev_logging`
Also changed the structure of the `_log` function to add `__wrapped__` and `_is_logged` parameters to be able to catch wrapped functions and remove the wrapper later without having to reload the module.
Test coverage is important. 
The other changes are motivated by code hygiene and philosophy. You shouldn't have to reload your module to remove the wrapped function.
```bash
pytest tests/util/test_dev_logging.py --cov=climakitae.util.dev_logging --cov-report term-missing
```
> Test Coverage for `util.dev_logging`

- climakitae/util/cluster.py
- tests/util/test_cluster.py
Added test coverage for `util.cluster`
Tests are important 
```bash
pytest tests/util/test_cluster.py --cov=climakitae.util.cluster --cov-report term-missing
```
> Test coverage for `climakitae.util.cluster`

- climakitae/core/data_export.py
- tests/data_export/test_data_export.py
I've added tests for core/data_export.py along with type hints.
Increases test coverage to 77%. Currently at 440 statements, 103 missing. Coverage could be increased by refactoring write_tmy_file() to expose internal functions.
I did not test _grab_dem_elev_m. According to Victoria the API accessed by this function currently does not work reliably, and this function may be deprecated. Work is planned to address it this summer.
```
pip install pytest 
pytest tests/data_export/ --cov=climakitae.core.data_export --cov-report term-missing
```
I've tested the 'export' function in the average_meteorological_year notebook to check that it worked as before.
> Tests for data_export.py

- climakitae/util/generate_gwl_tables.py
- tests/util/test_generate_gwl_tables.py
I added a test for the function get_sims_on_aws() in generate_gwl_tables.py. This only gets coverage to 19% (184 statements, 149 missing). The main() function does not look straightforward to test in its current form, but could possibly be refactored for better testing.
I also have added type hints and fixes for a pandas ChainedAssignment warning and numpy np.NaN warning.
This work improves the test coverage of generate_gwl_tables.py.
```
pytest tests/util/ --cov=climakitae.util.generate_gwl_tables --cov-report term-missing  # VSCode terminal
pytest tests/util/ --cov=util.generate_gwl_tables --cov-report term-missing              # Jupyter Hub
```
I don't see any notebooks that use this particular script.
> Test for util/generate_gwl_tables.py

- climakitae/util/generate_gwl_tables_unc.py
- tests/util/test_generate_gwl_tables_unc.py
Complete refactor of `climakitae.util.generate_gwl_tables_unc` to enable testing.
Test suite at 95% coverage for `climakitae.util.generate_gwl_tables_unc`.
Code for `generate_gwl_tables_unc` was previously a bunch of nested functions inside `main()` preventing effective testing. This was done in order to increase the ability to share information between functions, so the obvious choice for a refactor was to build a class that generates this file. So now we have a class that generates this file.
And tests because tests are good.
navigate to your local installation of `climakitae` (an env where you've run `pip install .` or `pip install climakitae`).
move into the utils folder and run
`python generate_gwl_tables_unc.py --test`
if you do not provide the test flag it will attempt to run all …
> Test Coverage for `util.generate_gwl_tables_unc.py`

- docs/index.rst
Remove outdated text about "working toward an alpha release" in our readthedocs page 
Out of date text
Confirm that you like the updated text. The new text is in the "notes" box. 
You can build the docs on your local machine if you'd like. Follow the instructions [here](https://github.com/cal-adapt/climakitae/blob/main/docs/README.md). 
Or, here's a screenshot of what it looks like:
> Improve wording in readthedocs page ("alpha release") 

- climakitae/util/utils.py
- tests/create_test_dataset.py
- tests/timeseriestools/test_timeseriestools_monthly.py
Fixed area weighted average function, and two other places in tests that area mean was taken incorrectly
Function for taking area weighted mean took lat and lon means consecutively rather than simultaneously, which can produce incorrect results.
Try taking a mean with the function
> fixed area mean

- climakitae/core/data_interface.py
- climakitae/core/data_load.py
This PR adds the option to select cells that are touching the selection area as opposed to only withing the selection area. Adds `all_touched` option to `DataParameters`, `get_data` and then that logic is processed in `data_load` depending on the option.
Users have requested the ability to select cells touching the edge of their service area. Should fix the not selecting any cell if the latitude, longitude box is too small as well.
Check out branch on HUB and run through the basic_data_access notebook and add the optional parameter.
- [ x ] New feature (non-breaking change which adds functionality)
> Add `all_touched` spatial filtering option to `DataParameters`, `get_data`, `data_load`

- climakitae/util/utils.py
- tests/util/test_utils.py
This PR adds `clip_to_shapefile` to util.utils and adds corresponding unit tests. This function uses rioxarray.clip under-the-hood and should work on any shapefile with a valid CRS. Rioxarray already does a lot of data validation and checking so the only validation I'm doing is making sure the input datasets have a CRS set. I add some helpful hints for common errors, which are often due to issues with the CRS or the grid size.
This change gives AE users the ability to clip AE data to a shapefile of their choosing. 
```
pip install pytest
pytest tests/util/test_utils.py
```
Testers can also grab a shapefile and try out the function in AE. Install this branch first.
Here's an example with the [TIGER/Line county shapefile](https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2024&laye …
> Add clip_to_shapefile function

- tests/data_load/test_data_load.py
Move the long-running (3+ s) tests in the data_load test submodule to the advanced tier.
Streamline automated testing by removing long-running tests from default set.
Run tests using marker:
`pytest -vv --durations=0 -m "not advanced"`
`pytest -vv --durations=0 -m advanced`
To trigger elevated tests on GitHub PRs simply set the label to Advanced Testing.
> Move data load tests to advanced tier

- climakitae/explore/agnostic.py
Readd removed `_round_to_nearest_half` function that is actually referenced still.
Fix broken code!
Run agnostic tools
> Readd removed `_round_to_nearest_half`

- climakitae/core/data_load.py
- setup.cfg
Added `xsdba` to `setup.cfg` for proper pip install from cli. 
`xclim` split `sdba` into it's own package, this is a temporary fix that will cause a user warning for a little bit until we do a full migration. 
Checkout this branch, then run the following on a linux machine:
```bash
pip install uv
uv venv --python 3.11
source .venv/bin/activate
uv pip install -e .
uv pip install climakitaegui
uv run python
>>> from climakitaegui.explore.amy import lineplot_from_amy_data
```
you should see a UserWarning and not an import error.
Once this is merged to main it should resolve the issue with the `climakitaegui` import since `climakitaegui` has `climakitae` as a dependency.
> Fix issue with pip installing climakitae due to xclim/xsdba migration

- .github/workflows/ci-main.yml
- README.md
main ci workflow now writes an xml report and ships that report off to [codecov.io](https://app.codecov.io/gh/cal-adapt/climakitae] for monitoring via a dashboard. Readme now also features a badge that gives an overall summary of the code coverage as reported back by codecov.
This allows us to stop running our code coverage manually and gives us a monitored history of coverage starting today. This will make project management easier and reduce dev time spent running the report code by hand.
Head over to the [branch](https://github.com/cal-adapt/climakitae/tree/feature/code-cov) and double check that the badge at the top of the README displays correctly. And head to the dashboard linked above to browse around and look at the report.
> [FEATURE] Automatic test coverage monitoring with `codecov.io`

- climakitae/util/warming_levels.py
Ensure that WL data does not start before 1981, since AE catalog data starts in Sept 1980 (can throw off WL calculations since the actual time axis is removed in WL data objects, so it is difficult to determine what month the data starts in).
We want to look at temporal trends in WL data that make sense if a dummy time is added to the WL obj, which means that we need to make sure data starts at Jan 1.
Pull Air Temperature at 2m data for EC-Earth3, EC-Earth3-Veg, or any GCM, at a WL that reaches that level of warming before 1995. Then, plot the data on a time axis and make sure that the cycle is following proper trends (i.e. add dummy time to wl to the data object, and make sure winter is the coldest and summer is the hottest).
**Alternatively**, this …
> Ensure WL data does not start before 1981

- climakitae/core/data_load.py
Fixing a bug where the dew point temperature derived data would not successfully have units converted to selected units. This bug may potentially affected other derived variables. 
I've rearranged L1335-1346 so that the unit conversion happens before copying the data attributes from the selections object. This is because the data array units would be overwritten by the units in the selections object, which affected the subsequent unit conversion.
Need to be able to request dew point temperature in units other than K.
Try loading dew point temperature or other derived variables in different units:
```
from climakitae.core.data_interface import get_data
dewpt_data = get_data(
variable="Dew point temperature",
resolution="9 km",
timescale="hourly",
data_type="Gridded",
units="degC", …
```
> Fix unit conversion bug for derived variables

- climakitae/data/variable_descriptions.csv
1. Daily WRF variables `t`, `u`, and `v` display name descriptions were revised so they do not conflict with other identically named variables. 
2. I sorted the table so now it if fixed in this order: Dynamical hourly -> monthly; Statistical daily -> monthly; Dynamical derived variables hourly -> monthly 
`t` specifically was breaking a pytest because it also had the same display name as `t2`. Have posed a question to @neilSchroeder and @acordonez about naming conventions. 
Make sure pytest doesn't fail now!
> Revise specific WRF variable descriptions that cause test failure

- tests/new_core/test_boundaries.py
Adding test coverage for Boundaries class for 95% test coverage.
Test coverage is great.
Check that all tests are passing in ci, run
```bash
python -m pytest tests/new_core/test_boundaries.py --cov=climakitae
```
to see that all tests pass.
> add boundary tests

- climakitae/core/data_interface.py
Update the scenario type hint in get_data.
get_data can take either a string or list of strings for scenario (e.g. ["Historical Climate", "SSP 3-7.0"] or "Historical Climate" are both valid options).
Check that unit tests pass
Test a get_data call, e.g.
```
from climakitae.core.data_interface import get_data
data = get_data(
variable="Air Temperature at 2m",
resolution="9 km",
timescale="hourly",
data_type="Gridded",
units="degC",
scenario= ["Historical Climate", "SSP 3-7.0"],
time_slice=(1990, 1999),
)
```
> Update type hint in get_data

- climakitae/explore/vulnerability.py
- tests/vulnerability/test_vulnerability.py
One_in_x is checked and converted to a list as needed in _metric_agg. None is not converted to a list in cava_data because that affects how validate_params() works.
We're now down to 77% for test coverage but I have added a test for this particular change.
Gets unit tests passing for vulnerability
Check that test run in CI. Check that tests pass locally using:
`python -m pytest tests/vulnerability/test_vulnerability.py --cov=climakitae/explore/ --cov-report=term-missing`
> Bugfix for cava_data one_in_x
